// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zPutPreferencesChatBody = z.object({
    modelId: z.string().nullable(),
    configSelections: z.record(z.string(), z.unknown()),
    continuationBehavior: z.enum(['queue', 'steer']).optional()
});

export const zPutPreferencesJarvisBody = z.object({
    runtimeKind: z.string().min(1).optional(),
    profileId: z.string().nullable(),
    model: z.string().optional(),
    thinkingLevel: z.enum([
        'minimal',
        'low',
        'medium',
        'high',
        'xhigh'
    ])
});

export const zPostWorkspacesBody = z.object({
    name: z.string().min(1).regex(/.*\S.*/),
    path: z.string().min(1).regex(/.*\S.*/)
});

export const zPostWorkspacesFromDirectoryBody = z.object({
    path: z.string().min(1).regex(/.*\S.*/)
});

export const zGetWorkspacesResolveQuery = z.object({
    path: z.string().min(1).regex(/.*\S.*/)
});

export const zGetWorkspacesByIdFilesPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesChildrenPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesChildrenQuery = z.object({
    path: z.string().optional()
});

export const zGetWorkspacesByIdFilesSearchPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesSearchQuery = z.object({
    q: z.string().optional(),
    limit: z.number().gte(1).lte(100).optional()
});

export const zGetWorkspacesByIdFilesEventsPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesContentPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesContentQuery = z.object({
    path: z.string().min(1).regex(/.*\S.*/)
});

export const zPutWorkspacesByIdFilesContentBody = z.object({
    path: z.string().min(1).regex(/.*\S.*/),
    content: z.string(),
    confirmedNonCradleOwnedWrite: z.boolean()
});

export const zPutWorkspacesByIdFilesContentPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesInfoPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesInfoQuery = z.object({
    path: z.string().min(1).regex(/.*\S.*/)
});

export const zGetWorkspacesByIdFilesRawPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesRawQuery = z.object({
    path: z.string().min(1).regex(/.*\S.*/)
});

export const zGetWorkspacesByIdFilesRenditionPdfPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdFilesRenditionPdfQuery = z.object({
    path: z.string().min(1).regex(/.*\S.*/)
});

export const zPostWorkspacesByIdFilesFileBody = z.object({
    path: z.string().min(1).regex(/.*\S.*/),
    confirmedNonCradleOwnedWrite: z.boolean()
});

export const zPostWorkspacesByIdFilesFilePath = z.object({
    id: z.string().min(1)
});

export const zPostWorkspacesByIdFilesFolderBody = z.object({
    path: z.string().min(1).regex(/.*\S.*/),
    confirmedNonCradleOwnedWrite: z.boolean()
});

export const zPostWorkspacesByIdFilesFolderPath = z.object({
    id: z.string().min(1)
});

export const zPatchWorkspacesByIdFilesPathBody = z.object({
    sourcePath: z.string().min(1).regex(/.*\S.*/),
    destinationPath: z.string().min(1).regex(/.*\S.*/),
    confirmedNonCradleOwnedWrite: z.boolean()
});

export const zPatchWorkspacesByIdFilesPathPath = z.object({
    id: z.string().min(1)
});

export const zDeleteWorkspacesByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchWorkspacesByIdBody = z.object({
    name: z.string().min(1).regex(/.*\S.*/).optional(),
    pinned: z.boolean().optional()
});

export const zPatchWorkspacesByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetFilesystemBrowseQuery = z.object({
    path: z.string().optional()
});

export const zGetUsageDailyQuery = z.object({
    days: z.union([
        z.string(),
        z.number().gte(1)
    ]).optional()
});

export const zGetUsageSessionsBySessionIdPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetUsageCostSummaryQuery = z.object({
    from: z.iso.date().optional(),
    to: z.iso.date().optional()
});

export const zGetUsageCostSessionsQuery = z.object({
    from: z.iso.date().optional(),
    to: z.iso.date().optional()
});

export const zGetUsageCostDailyQuery = z.object({
    from: z.iso.date().optional(),
    to: z.iso.date().optional()
});

export const zDeleteProfilesByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetProfilesByIdPath = z.object({
    id: z.string().min(1)
});

export const zPutProfilesByIdBody = z.object({
    name: z.string().min(1),
    providerKind: z.enum([
        'openai-compatible',
        'anthropic',
        'universal'
    ]),
    enabled: z.boolean(),
    config: z.record(z.string(), z.unknown()),
    credentialRef: z.string().min(1).nullish(),
    iconSlug: z.string().nullish()
});

export const zPutProfilesByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchProfilesByIdIconBody = z.object({
    iconSlug: z.string().nullable()
});

export const zPatchProfilesByIdIconPath = z.object({
    id: z.string().min(1)
});

export const zPatchProfilesByIdCustomModelsBody = z.object({
    models: z.array(z.object({
        id: z.string().min(1),
        label: z.string().optional(),
        capabilities: z.object({
            contextWindow: z.number().optional(),
            maxOutput: z.number().optional(),
            inputModalities: z.array(z.string()).optional(),
            outputModalities: z.array(z.string()).optional(),
            reasoning: z.boolean().optional(),
            toolCall: z.boolean().optional(),
            temperature: z.boolean().optional(),
            structuredOutput: z.boolean().optional(),
            cost: z.object({
                input: z.number().optional(),
                output: z.number().optional(),
                cacheRead: z.number().optional(),
                cacheWrite: z.number().optional()
            }).optional(),
            family: z.string().optional(),
            knowledgeCutoff: z.string().optional(),
            releaseDate: z.string().optional(),
            registryMatch: z.enum([
                'exact',
                'fuzzy',
                'manual',
                'alias',
                'unmatched'
            ]).optional(),
            registryModelId: z.string().optional(),
            registryModelLabel: z.string().optional()
        }).optional()
    }))
});

export const zPatchProfilesByIdCustomModelsPath = z.object({
    id: z.string().min(1)
});

export const zDeleteProviderTargetsByProviderTargetIdPath = z.object({
    providerTargetId: z.string().min(1)
});

export const zPutProviderTargetsByProviderTargetIdBody = z.object({
    displayName: z.string().min(1),
    providerKind: z.enum([
        'openai-compatible',
        'anthropic',
        'universal'
    ]),
    enabled: z.boolean().optional(),
    connectionConfig: z.record(z.string(), z.unknown()),
    credentialRef: z.string().nullish(),
    iconSlug: z.string().nullish()
});

export const zPutProviderTargetsByProviderTargetIdPath = z.object({
    providerTargetId: z.string().min(1)
});

export const zGetProviderTargetsByProviderTargetIdModelSettingsPath = z.object({
    providerTargetId: z.string().min(1)
});

export const zPatchProviderTargetsByProviderTargetIdModelVisibilityBody = z.object({
    enabledModels: z.array(z.string().min(1))
});

export const zPatchProviderTargetsByProviderTargetIdModelVisibilityPath = z.object({
    providerTargetId: z.string().min(1)
});

export const zPatchProviderTargetsByProviderTargetIdCustomModelsBody = z.object({
    models: z.array(z.object({
        id: z.string().min(1),
        label: z.string().optional()
    }))
});

export const zPatchProviderTargetsByProviderTargetIdCustomModelsPath = z.object({
    providerTargetId: z.string().min(1)
});

export const zPostExternalProviderSourcesBySourceKeyRefreshPath = z.object({
    sourceKey: z.string().min(1)
});

export const zGetExternalProviderSourcesBySourceKeyRecordsByExternalRecordIdRuntimeTargetPath = z.object({
    sourceKey: z.string().min(1),
    externalRecordId: z.string().min(1)
});

export const zPatchExternalProviderSourcesBySourceKeyRecordsByExternalRecordIdRuntimeTargetBody = z.object({
    enabled: z.boolean()
});

export const zPatchExternalProviderSourcesBySourceKeyRecordsByExternalRecordIdRuntimeTargetPath = z.object({
    sourceKey: z.string().min(1),
    externalRecordId: z.string().min(1)
});

export const zPostExternalWorkImportPreviewBody = z.object({
    includeHome: z.boolean().optional(),
    cwds: z.array(z.string().min(1)).optional(),
    sourceApps: z.array(z.enum([
        'claude',
        'codex',
        'cursor',
        'windsurf',
        'gemini',
        'unknown'
    ])).optional(),
    limitPerSource: z.number().gte(1).lte(500).optional()
});

export const zPostExternalWorkImportUploadPreviewBody = z.object({
    files: z.array(z.object({
        sourceApp: z.enum([
            'claude',
            'codex',
            'cursor',
            'windsurf',
            'gemini',
            'unknown'
        ]),
        path: z.string().min(1),
        content: z.string(),
        workspacePath: z.string().min(1).nullish(),
        modifiedAt: z.number().nullish()
    }))
});

export const zPostExternalWorkImportImportBody = z.object({
    items: z.array(z.object({
        id: z.string(),
        sourceApp: z.enum([
            'claude',
            'codex',
            'cursor',
            'windsurf',
            'gemini',
            'unknown'
        ]),
        sourceScope: z.enum(['server', 'electron-upload']),
        sourceKind: z.enum([
            'settings',
            'project',
            'session',
            'instruction',
            'mcp',
            'command',
            'hook',
            'skill',
            'plugin',
            'subagent'
        ]),
        title: z.string(),
        summary: z.string().nullable(),
        sourcePath: z.string().nullable(),
        externalId: z.string(),
        fingerprint: z.string(),
        workspacePath: z.string().nullable(),
        createdAt: z.number().nullable(),
        updatedAt: z.number().nullable(),
        duplicate: z.boolean(),
        duplicateImportId: z.string().nullable(),
        importable: z.boolean(),
        reason: z.string().nullable(),
        payloadJson: z.string()
    }))
});

export const zPostSecretsBody = z.object({
    kind: z.string().min(1),
    label: z.string().min(1),
    secret: z.string().min(1)
});

export const zDeleteSecretsByIdPath = z.object({
    id: z.string().min(1)
});

export const zDeleteModelRegistryMappingsByModelIdPath = z.object({
    modelId: z.string().min(1)
});

export const zPutModelRegistryMappingsByModelIdBody = z.object({
    modelId: z.string().min(1),
    registryModelId: z.string().min(1).optional(),
    matchType: z.enum(['manual', 'alias']).optional(),
    model: z.object({
        id: z.string().min(1),
        name: z.string().optional(),
        limit: z.object({
            context: z.number().optional(),
            output: z.number().optional()
        }).optional(),
        modalities: z.object({
            input: z.array(z.string()).optional(),
            output: z.array(z.string()).optional()
        }).optional(),
        reasoning: z.boolean().optional(),
        tool_call: z.boolean().optional(),
        temperature: z.boolean().optional(),
        structured_output: z.boolean().optional(),
        cost: z.object({
            input: z.number().optional(),
            output: z.number().optional(),
            cache_read: z.number().optional(),
            cache_write: z.number().optional()
        }).optional(),
        family: z.string().optional(),
        knowledge: z.string().optional(),
        release_date: z.string().optional()
    }).optional()
});

export const zPutModelRegistryMappingsByModelIdPath = z.object({
    modelId: z.string().min(1)
});

export const zPostProvidersModelsBody = z.object({
    providerKind: z.enum([
        'openai-compatible',
        'anthropic',
        'universal'
    ]),
    label: z.string().min(1),
    config: z.object({
        baseUrl: z.string().optional(),
        model: z.string().optional(),
        enabledModels: z.array(z.string()).optional(),
        maxMessages: z.number().optional()
    }),
    secretRef: z.string().min(1).nullish(),
    profileId: z.string().min(1).nullish(),
    providerTargetKind: z.union([
        z.string(),
        z.unknown()
    ]).optional(),
    providerTargetId: z.string().min(1).nullish()
});

export const zGetProvidersTargetsByProviderTargetIdModelsCachePath = z.object({
    providerTargetId: z.string().min(1)
});

export const zGetProvidersByProfileIdModelsCachePath = z.object({
    profileId: z.string().min(1)
});

export const zPostProvidersModelLookupBody = z.object({
    modelId: z.string().min(1)
});

export const zPostProvidersModelSearchBody = z.object({
    query: z.string().min(1)
});

export const zGetAgentsQuery = z.object({
    enabled: z.string().optional(),
    providerTargetId: z.string().optional()
});

export const zPostAgentsBody = z.object({
    name: z.string().min(1),
    description: z.string().nullish(),
    avatarStyle: z.string().min(1),
    avatarSeed: z.string().min(1),
    providerTargetId: z.string().nullish(),
    modelId: z.string().nullish(),
    thinkingEffort: z.enum([
        'low',
        'medium',
        'high',
        'xhigh',
        'auto'
    ]).optional(),
    runtimeKind: z.string().min(1).optional(),
    configJson: z.string().optional()
});

export const zDeleteAgentsByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetAgentsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchAgentsByIdBody = z.object({
    name: z.string().min(1).optional(),
    description: z.string().nullish(),
    avatarStyle: z.string().min(1).optional(),
    avatarSeed: z.string().min(1).optional(),
    providerTargetId: z.string().nullish(),
    modelId: z.string().nullish(),
    thinkingEffort: z.enum([
        'low',
        'medium',
        'high',
        'xhigh',
        'auto'
    ]).optional(),
    runtimeKind: z.string().min(1).optional(),
    configJson: z.string().optional(),
    enabled: z.boolean().optional()
});

export const zPatchAgentsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPostAgentsImportLocalConfigBody = z.object({
    includeProcessEnv: z.boolean().optional(),
    candidateIds: z.array(z.string().min(1)).optional()
});

export const zPostAgentsImportLocalConfigPreviewBody = z.object({
    includeProcessEnv: z.boolean().optional(),
    candidateIds: z.array(z.string().min(1)).optional()
});

export const zGetAutomationsQuery = z.object({
    workspaceId: z.string().min(1).optional(),
    enabled: z.boolean().optional()
});

export const zPostAutomationsBody = z.object({
    id: z.string().min(1).optional(),
    workspaceId: z.string().min(1).nullish(),
    title: z.string().min(1),
    description: z.string().optional(),
    enabled: z.boolean().optional(),
    trigger: z.object({
        type: z.string(),
        rrule: z.string().min(1),
        timezone: z.string().min(1),
        misfirePolicy: z.enum(['skip', 'run_latest']).optional()
    }),
    recipe: z.object({
        kind: z.string(),
        prompt: z.string().min(1),
        inputs: z.array(z.union([
            z.object({
                type: z.string(),
                path: z.string().min(1)
            }),
            z.object({
                type: z.string(),
                name: z.string().min(1),
                content: z.string()
            }),
            z.object({
                type: z.string(),
                name: z.string().min(1),
                content: z.string()
            }),
            z.object({
                type: z.string(),
                url: z.string().min(1)
            })
        ])),
        artifactRequests: z.array(z.object({
            kind: z.enum([
                'markdown',
                'text',
                'json',
                'file_ref'
            ]),
            name: z.string().min(1),
            description: z.string().optional()
        })),
        agentId: z.string().min(1).optional(),
        providerTargetId: z.string().min(1).optional(),
        runtimeKind: z.string().min(1).optional(),
        modelId: z.string().min(1).optional(),
        thinkingEffort: z.enum([
            'low',
            'medium',
            'high',
            'xhigh'
        ]).optional()
    }),
    createdByKind: z.enum([
        'agent',
        'user',
        'system'
    ]).optional(),
    createdById: z.string().min(1).nullish()
});

export const zDeleteAutomationsByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetAutomationsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchAutomationsByIdBody = z.object({
    title: z.string().min(1).optional(),
    description: z.string().optional(),
    trigger: z.object({
        type: z.string(),
        rrule: z.string().min(1),
        timezone: z.string().min(1),
        misfirePolicy: z.enum(['skip', 'run_latest']).optional()
    }).optional(),
    recipe: z.object({
        kind: z.string(),
        prompt: z.string().min(1),
        inputs: z.array(z.union([
            z.object({
                type: z.string(),
                path: z.string().min(1)
            }),
            z.object({
                type: z.string(),
                name: z.string().min(1),
                content: z.string()
            }),
            z.object({
                type: z.string(),
                name: z.string().min(1),
                content: z.string()
            }),
            z.object({
                type: z.string(),
                url: z.string().min(1)
            })
        ])),
        artifactRequests: z.array(z.object({
            kind: z.enum([
                'markdown',
                'text',
                'json',
                'file_ref'
            ]),
            name: z.string().min(1),
            description: z.string().optional()
        })),
        agentId: z.string().min(1).optional(),
        providerTargetId: z.string().min(1).optional(),
        runtimeKind: z.string().min(1).optional(),
        modelId: z.string().min(1).optional(),
        thinkingEffort: z.enum([
            'low',
            'medium',
            'high',
            'xhigh'
        ]).optional()
    }).optional(),
    createdByKind: z.enum([
        'agent',
        'user',
        'system'
    ]).optional(),
    createdById: z.string().min(1).nullish()
});

export const zPatchAutomationsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPostAutomationsByIdEnablePath = z.object({
    id: z.string().min(1)
});

export const zPostAutomationsByIdDisablePath = z.object({
    id: z.string().min(1)
});

export const zPostAutomationsByIdRunBody = z.object({
    occurrenceKey: z.string().min(1).optional(),
    scheduledFor: z.number().optional()
});

export const zPostAutomationsByIdRunPath = z.object({
    id: z.string().min(1)
});

export const zGetAutomationsByIdRunsPath = z.object({
    id: z.string().min(1)
});

export const zGetAutomationsByIdRunsByRunIdPath = z.object({
    id: z.string().min(1),
    runId: z.string().min(1)
});

export const zGetAutomationsByIdRunsByRunIdArtifactsPath = z.object({
    id: z.string().min(1),
    runId: z.string().min(1)
});

export const zGetAutomationsByIdArtifactsPath = z.object({
    id: z.string().min(1)
});

export const zGetAutomationsByIdArtifactsByArtifactIdPath = z.object({
    id: z.string().min(1),
    artifactId: z.string().min(1)
});

export const zGetSessionsQuery = z.object({
    workspaceId: z.string().min(1).optional(),
    archived: z.boolean().optional()
});

export const zPostSessionsBody = z.object({
    workspaceId: z.string().min(1).nullish(),
    title: z.string().min(1),
    providerTargetId: z.string().min(1).nullish(),
    agentId: z.string().min(1).optional(),
    runtimeKind: z.string().min(1).optional(),
    id: z.string().optional()
});

export const zDeleteSessionsByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetSessionsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchSessionsByIdBody = z.object({
    title: z.string().min(1).optional(),
    pinned: z.boolean().optional(),
    providerTargetId: z.string().min(1).nullish(),
    modelId: z.string().min(1).nullish()
});

export const zPatchSessionsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPostSessionsByIdArchiveBody = z.object({
    archived: z.boolean()
});

export const zPostSessionsByIdArchivePath = z.object({
    id: z.string().min(1)
});

export const zGetSessionsByIdMessagesPath = z.object({
    id: z.string().min(1)
});

export const zGetSessionsByIdExportMarkdownPath = z.object({
    id: z.string().min(1)
});

export const zDeleteSessionsByIdLinkedIssuePath = z.object({
    id: z.string().min(1)
});

export const zGetSessionsByIdLinkedIssuePath = z.object({
    id: z.string().min(1)
});

export const zPostSessionsByIdLinkedIssueBody = z.object({
    issueId: z.string().min(1)
});

export const zPostSessionsByIdLinkedIssuePath = z.object({
    id: z.string().min(1)
});

export const zGetSessionAwaitsQuery = z.object({
    sessionId: z.string().min(1)
});

export const zPostSessionAwaitsBody = z.object({
    chatSessionId: z.string().min(1),
    workspaceId: z.string().min(1),
    source: z.string().min(1),
    filterJson: z.string().min(1),
    reason: z.string().nullish(),
    expiresAt: z.number().nullish(),
    fireAt: z.number().nullish()
});

export const zGetSessionAwaitsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPostSessionAwaitsByIdCancelPath = z.object({
    id: z.string().min(1)
});

export const zPostSessionAwaitsByIdTriggerBody = z.object({
    resumeText: z.string().min(1).regex(/.*\S.*/),
    resumePayloadJson: z.string().nullish()
});

export const zPostSessionAwaitsByIdTriggerPath = z.object({
    id: z.string().min(1)
});

export const zPostSessionAwaitsByIdRetryDeliveryBody = z.object({
    resumeText: z.string().min(1).regex(/.*\S.*/).optional(),
    resumePayloadJson: z.string().nullish()
});

export const zPostSessionAwaitsByIdRetryDeliveryPath = z.object({
    id: z.string().min(1)
});

export const zGetSessionAwaitsSummaryQuery = z.object({
    sessionId: z.string().min(1)
});

export const zGetSessionAwaitsDiscoveredReposQuery = z.object({
    workspaceId: z.string().min(1)
});

export const zGetSessionAwaitsAvailableChecksQuery = z.object({
    owner: z.string().min(1),
    repo: z.string().min(1)
});

export const zPostSessionAwaitsByIdBypassCheckBody = z.object({
    checkName: z.string().min(1)
});

export const zPostSessionAwaitsByIdBypassCheckPath = z.object({
    id: z.string().min(1)
});

export const zGetSessionAwaitsByIdLiveStatusPath = z.object({
    id: z.string().min(1)
});

export const zGetSessionAwaitsBypassRulesQuery = z.object({
    workspaceId: z.string().min(1)
});

export const zPostSessionAwaitsBypassRulesBody = z.object({
    workspaceId: z.string().min(1),
    repo: z.string().min(1),
    checkPattern: z.string().min(1)
});

export const zDeleteSessionAwaitsBypassRulesByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchSessionAwaitsBypassRulesByIdBody = z.object({
    enabled: z.boolean()
});

export const zPatchSessionAwaitsBypassRulesByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetIssuesStatusesQuery = z.object({
    workspaceId: z.string().min(1)
});

export const zPostIssuesStatusesBody = z.object({
    workspaceId: z.string().min(1),
    name: z.string().min(1),
    color: z.string().nullish(),
    category: z.enum([
        'triage',
        'backlog',
        'unstarted',
        'started',
        'completed',
        'canceled'
    ]).optional()
});

export const zPostIssuesStatusesReorderBody = z.object({
    workspaceId: z.string().min(1),
    orderedIds: z.array(z.string())
});

export const zDeleteIssuesStatusesByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchIssuesStatusesByIdBody = z.object({
    name: z.string().min(1).optional(),
    color: z.string().nullish()
});

export const zPatchIssuesStatusesByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetIssuesMilestonesQuery = z.object({
    workspaceId: z.string().min(1)
});

export const zPostIssuesMilestonesBody = z.object({
    workspaceId: z.string().min(1),
    title: z.string().min(1),
    description: z.string().nullish(),
    dueDate: z.number().nullish(),
    status: z.enum(['open', 'closed']).optional()
});

export const zDeleteIssuesMilestonesByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchIssuesMilestonesByIdBody = z.object({
    title: z.string().min(1).optional(),
    description: z.string().nullish(),
    dueDate: z.number().nullish(),
    status: z.enum(['open', 'closed']).optional()
});

export const zPatchIssuesMilestonesByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetIssuesSearchQuery = z.object({
    q: z.string(),
    limit: z.string().optional()
});

export const zGetIssuesQuery = z.object({
    workspaceId: z.string().min(1),
    milestoneId: z.string().optional(),
    parentIssueId: z.string().optional(),
    priority: z.string().optional(),
    labels: z.union([
        z.array(z.string()),
        z.string()
    ]).optional(),
    statusId: z.string().optional()
});

export const zPostIssuesBody = z.object({
    workspaceId: z.string().min(1),
    title: z.string().min(1),
    description: z.string().nullish(),
    priority: z.enum([
        'none',
        'low',
        'medium',
        'high',
        'urgent'
    ]).optional(),
    labels: z.array(z.string()).optional(),
    milestoneId: z.string().nullish(),
    parentIssueId: z.string().nullish(),
    statusId: z.string().nullish(),
    statusName: z.string().min(1).nullish(),
    dueDate: z.number().nullish(),
    assigneeKind: z.string().nullish(),
    assigneeId: z.string().nullish()
});

export const zDeleteIssuesByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetIssuesByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchIssuesByIdBody = z.object({
    title: z.string().min(1).optional(),
    description: z.string().nullish(),
    priority: z.enum([
        'none',
        'low',
        'medium',
        'high',
        'urgent'
    ]).optional(),
    labels: z.array(z.string()).optional(),
    milestoneId: z.string().nullish(),
    parentIssueId: z.string().nullish(),
    statusId: z.string().nullish(),
    statusName: z.string().min(1).nullish(),
    assigneeKind: z.string().nullish(),
    assigneeId: z.string().nullish(),
    dueDate: z.number().nullish(),
    order: z.number().optional()
});

export const zPatchIssuesByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchIssuesBulkBody = z.object({
    issueIds: z.array(z.string()),
    update: z.object({
        statusId: z.string().nullish(),
        priority: z.enum([
            'none',
            'low',
            'medium',
            'high',
            'urgent'
        ]).optional(),
        labels: z.array(z.string()).optional(),
        milestoneId: z.string().nullish(),
        assigneeKind: z.string().nullish(),
        assigneeId: z.string().nullish(),
        dueDate: z.number().nullish()
    })
});

export const zPatchIssuesByIdStatusByStatusNamePath = z.object({
    id: z.string().min(1),
    statusName: z.string().min(1)
});

export const zGetIssuesByIdFieldChangesPath = z.object({
    id: z.string().min(1)
});

export const zGetIssuesByIdCommentsPath = z.object({
    id: z.string().min(1)
});

export const zPostIssuesByIdCommentsBody = z.object({
    content: z.string().min(1)
});

export const zPostIssuesByIdCommentsPath = z.object({
    id: z.string().min(1)
});

export const zDeleteIssuesCommentsByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetIssuesByIdRelationsPath = z.object({
    id: z.string().min(1)
});

export const zPostIssuesRelationsBody = z.object({
    sourceIssueId: z.string().min(1),
    targetIssueId: z.string().min(1),
    type: z.enum([
        'blocks',
        'duplicates',
        'relates_to'
    ])
});

export const zDeleteIssuesRelationsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPostIssuesByIdContextRefsBody = z.object({
    ref: z.string().min(1)
});

export const zPostIssuesByIdContextRefsPath = z.object({
    id: z.string().min(1)
});

export const zDeleteIssuesByIdContextRefsByIndexPath = z.object({
    id: z.string().min(1),
    index: z.string()
});

export const zGetKanbanBoardsQuery = z.object({
    workspaceId: z.string().optional()
});

export const zPostKanbanBoardsBody = z.object({
    workspaceId: z.string().min(1),
    name: z.string().min(1),
    filterConfig: z.string().nullish()
});

export const zDeleteKanbanBoardsByIdPath = z.object({
    id: z.string().min(1)
});

export const zPatchKanbanBoardsByIdBody = z.object({
    name: z.string().min(1).optional(),
    filterConfig: z.string().nullish()
});

export const zPatchKanbanBoardsByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetSearchThreadsQuery = z.object({
    query: z.string().min(1),
    workspaceId: z.string().optional(),
    limit: z.union([
        z.string(),
        z.number().gte(1)
    ]).optional(),
    snippetsPerHit: z.union([
        z.string(),
        z.number().gte(1)
    ]).optional()
});

export const zGetSearchChronicleQuery = z.object({
    query: z.string().min(1),
    workspaceId: z.string().optional(),
    limit: z.union([
        z.string(),
        z.number().gte(1)
    ]).optional()
});

export const zGetSkillsQuery = z.object({
    workspaceId: z.string().min(1).regex(/.*\S.*/).optional(),
    agentId: z.string().min(1).regex(/.*\S.*/).optional()
});

export const zPostSkillsBody = z.object({
    scope: z.enum([
        'builtin',
        'legacy',
        'global',
        'repository',
        'workspace',
        'agent'
    ]),
    name: z.string().min(1).regex(/.*\S.*/),
    description: z.string().min(1).regex(/.*\S.*/),
    body: z.string(),
    workspaceId: z.string().min(1).regex(/.*\S.*/).nullish(),
    agentId: z.string().min(1).regex(/.*\S.*/).nullish(),
    frontmatter: z.record(z.string(), z.unknown()).optional()
});

export const zDeleteSkillsDocumentQuery = z.object({
    scope: z.enum([
        'builtin',
        'legacy',
        'global',
        'repository',
        'workspace',
        'agent'
    ]),
    name: z.string().min(1).regex(/.*\S.*/),
    workspaceId: z.string().min(1).regex(/.*\S.*/).optional(),
    agentId: z.string().min(1).regex(/.*\S.*/).optional()
});

export const zGetSkillsDocumentQuery = z.object({
    scope: z.enum([
        'builtin',
        'legacy',
        'global',
        'repository',
        'workspace',
        'agent'
    ]),
    name: z.string().min(1).regex(/.*\S.*/),
    workspaceId: z.string().min(1).regex(/.*\S.*/).optional(),
    agentId: z.string().min(1).regex(/.*\S.*/).optional()
});

export const zPutSkillsDocumentBody = z.object({
    scope: z.enum([
        'builtin',
        'legacy',
        'global',
        'repository',
        'workspace',
        'agent'
    ]),
    name: z.string().min(1).regex(/.*\S.*/),
    workspaceId: z.string().min(1).regex(/.*\S.*/).nullish(),
    agentId: z.string().min(1).regex(/.*\S.*/).nullish(),
    document: z.object({
        name: z.string().min(1).regex(/.*\S.*/),
        description: z.string().min(1).regex(/.*\S.*/),
        body: z.string(),
        frontmatter: z.record(z.string(), z.unknown()).optional()
    })
});

export const zPostSkillsImportBody = z.object({
    scope: z.enum([
        'builtin',
        'legacy',
        'global',
        'repository',
        'workspace',
        'agent'
    ]),
    sourceDir: z.string().min(1).regex(/.*\S.*/),
    overwrite: z.boolean().optional(),
    workspaceId: z.string().min(1).regex(/.*\S.*/).nullish(),
    agentId: z.string().min(1).regex(/.*\S.*/).nullish()
});

export const zPostSkillsExportBody = z.object({
    scope: z.enum([
        'builtin',
        'legacy',
        'global',
        'repository',
        'workspace',
        'agent'
    ]),
    name: z.string().min(1).regex(/.*\S.*/),
    destinationDir: z.string().min(1).regex(/.*\S.*/),
    confirmedNonCradleOwnedWrite: z.boolean(),
    overwrite: z.boolean().optional(),
    workspaceId: z.string().min(1).regex(/.*\S.*/).nullish(),
    agentId: z.string().min(1).regex(/.*\S.*/).nullish()
});

export const zPostSkillsFetchSourceBody = z.object({
    source: z.string().min(1).regex(/.*\S.*/)
});

export const zPostSkillsImportFromFetchBody = z.object({
    sessionId: z.string().min(1).regex(/.*\S.*/),
    selectedDirs: z.array(z.string().min(1).regex(/.*\S.*/)).min(1),
    scope: z.enum([
        'builtin',
        'legacy',
        'global',
        'repository',
        'workspace',
        'agent'
    ]),
    overwrite: z.boolean().optional(),
    workspaceId: z.string().min(1).regex(/.*\S.*/).nullish(),
    agentId: z.string().min(1).regex(/.*\S.*/).nullish()
});

export const zPostSkillsCancelFetchBody = z.object({
    sessionId: z.string().min(1).regex(/.*\S.*/)
});

export const zGetWorkflowRulesByWorkspaceIdListPath = z.object({
    workspaceId: z.string().min(1)
});

export const zDeleteWorkflowRulesByWorkspaceIdPath = z.object({
    workspaceId: z.string().min(1)
});

export const zDeleteWorkflowRulesByWorkspaceIdQuery = z.object({
    agentProfileId: z.string().optional()
});

export const zGetWorkflowRulesByWorkspaceIdPath = z.object({
    workspaceId: z.string().min(1)
});

export const zGetWorkflowRulesByWorkspaceIdQuery = z.object({
    agentProfileId: z.string().optional()
});

export const zPutWorkflowRulesByWorkspaceIdBody = z.object({
    agentProfileId: z.string().nullish(),
    content: z.string()
});

export const zPutWorkflowRulesByWorkspaceIdPath = z.object({
    workspaceId: z.string().min(1)
});

export const zGetWorkspacesByIdGitStatusPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdGitBranchesPath = z.object({
    id: z.string().min(1)
});

export const zPostWorkspacesByIdGitBranchesBody = z.object({
    name: z.string().min(1),
    from: z.string().min(1).optional()
});

export const zPostWorkspacesByIdGitBranchesPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdGitRemotesPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdGitGraphPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdGitGraphQuery = z.object({
    limit: z.union([
        z.string(),
        z.number().gte(1)
    ]).optional()
});

export const zPostWorkspacesByIdGitCheckoutBody = z.object({
    branch: z.string().min(1)
});

export const zPostWorkspacesByIdGitCheckoutPath = z.object({
    id: z.string().min(1)
});

export const zPostWorkspacesByIdGitFetchPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdGitDiffPath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdGitDiffQuery = z.object({
    paths: z.string().optional()
});

export const zGetWorkspacesByIdGitMergeBasePath = z.object({
    id: z.string().min(1)
});

export const zGetWorkspacesByIdGitMergeBaseQuery = z.object({
    baseBranch: z.string().min(1)
});

export const zPostWorkspacesByIdPackBody = z.object({
    style: z.enum([
        'xml',
        'markdown',
        'plain'
    ]),
    compress: z.boolean(),
    include: z.string().min(1).optional(),
    ignore: z.string().min(1).optional(),
    removeComments: z.boolean().optional(),
    removeEmptyLines: z.boolean().optional()
});

export const zPostWorkspacesByIdPackPath = z.object({
    id: z.string().min(1)
});

export const zGetAcpRegistryByAgentIdDistributionTypesPath = z.object({
    agentId: z.string().min(1)
});

export const zDeleteAcpAgentsByAgentIdPath = z.object({
    agentId: z.string().min(1)
});

export const zGetAcpAgentsByAgentIdPath = z.object({
    agentId: z.string().min(1)
});

export const zDeleteAcpAgentsByAgentIdInstallationPath = z.object({
    agentId: z.string().min(1)
});

export const zPutAcpAgentsByAgentIdInstallationBody = z.object({
    distributionType: z.enum([
        'binary',
        'npx',
        'uvx'
    ])
});

export const zPutAcpAgentsByAgentIdInstallationPath = z.object({
    agentId: z.string().min(1)
});

export const zGetAcpAuditQuery = z.object({
    agentId: z.string().optional()
});

export const zGetAcpAgentsByAgentIdInstallPathPath = z.object({
    agentId: z.string().min(1)
});

export const zPostChatSessionsBySessionIdResponseBody = z.object({
    text: z.string().optional(),
    files: z.array(z.object({
        type: z.string(),
        mediaType: z.string().min(1),
        filename: z.string().optional(),
        url: z.string().min(1),
        providerMetadata: z.unknown().optional()
    })).optional(),
    contextParts: z.array(z.object({
        type: z.string(),
        name: z.string().min(1),
        path: z.string().min(1),
        scope: z.enum([
            'builtin',
            'legacy',
            'global',
            'repository',
            'workspace',
            'agent'
        ]),
        description: z.string().nullable(),
        position: z.number().gte(0).optional()
    })).optional(),
    messages: z.array(z.object({
        id: z.string(),
        role: z.enum(['user', 'assistant']),
        parts: z.array(z.object({
            type: z.string()
        })),
        metadata: z.unknown().optional()
    })).optional(),
    providerTargetId: z.string().optional(),
    modelId: z.string().optional(),
    thinkingEffort: z.enum([
        'low',
        'medium',
        'high',
        'xhigh'
    ]).optional(),
    permissionMode: z.enum(['bypassPermissions', 'plan']).optional()
});

export const zPostChatSessionsBySessionIdResponsePath = z.object({
    sessionId: z.string().min(1)
});

export const zPostChatSessionsBySessionIdBangCommandBody = z.object({
    command: z.string().min(1)
});

export const zPostChatSessionsBySessionIdBangCommandPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetChatSessionsBySessionIdStreamPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetChatSessionsBySessionIdQueuePath = z.object({
    sessionId: z.string().min(1)
});

export const zPostChatSessionsBySessionIdQueueBody = z.object({
    mode: z.enum(['queue', 'steer']),
    text: z.string().min(1).optional(),
    files: z.array(z.object({
        type: z.string(),
        mediaType: z.string().min(1),
        filename: z.string().optional(),
        url: z.string().min(1),
        providerMetadata: z.unknown().optional()
    })).optional(),
    contextParts: z.array(z.object({
        type: z.string(),
        name: z.string().min(1),
        path: z.string().min(1),
        scope: z.enum([
            'builtin',
            'legacy',
            'global',
            'repository',
            'workspace',
            'agent'
        ]),
        description: z.string().nullable(),
        position: z.number().gte(0).optional()
    })).optional(),
    providerTargetId: z.string().optional(),
    modelId: z.string().optional(),
    thinkingEffort: z.enum([
        'low',
        'medium',
        'high',
        'xhigh'
    ]).optional(),
    permissionMode: z.enum(['bypassPermissions', 'plan']).optional()
});

export const zPostChatSessionsBySessionIdQueuePath = z.object({
    sessionId: z.string().min(1)
});

export const zPostChatSessionsBySessionIdQueueReorderBody = z.object({
    queueItemIds: z.array(z.string().min(1))
});

export const zPostChatSessionsBySessionIdQueueReorderPath = z.object({
    sessionId: z.string().min(1)
});

export const zDeleteChatSessionsBySessionIdQueueByQueueItemIdPath = z.object({
    sessionId: z.string().min(1),
    queueItemId: z.string().min(1)
});

export const zGetChatDraftRuntimeCapabilitiesQuery = z.object({
    runtimeKind: z.string().min(1)
});

export const zGetChatSessionsBySessionIdCapabilitiesPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetChatSessionsBySessionIdUiSlotStatesPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetChatSessionsBySessionIdRuntimeStatusPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetChatSessionsBySessionIdCodexAppServerCapabilitiesPath = z.object({
    sessionId: z.string().min(1)
});

export const zPostChatSessionsBySessionIdCodexAppServerInvokeBody = z.object({
    method: z.string().min(1),
    params: z.unknown().optional(),
    providerTargetId: z.string().optional(),
    modelId: z.string().optional()
});

export const zPostChatSessionsBySessionIdCodexAppServerInvokePath = z.object({
    sessionId: z.string().min(1)
});

export const zPostChatSessionsBySessionIdCodexAppServerStreamBody = z.object({
    method: z.string().min(1),
    params: z.unknown().optional(),
    providerTargetId: z.string().optional(),
    modelId: z.string().optional(),
    closeOnMethods: z.array(z.string().min(1)).optional()
});

export const zPostChatSessionsBySessionIdCodexAppServerStreamPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetChatSessionsBySessionIdMessagesPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetChatRunsByRunIdTracePath = z.object({
    runId: z.string().min(1)
});

export const zGetChatRunsByRunIdSnapshotPath = z.object({
    runId: z.string().min(1)
});

export const zGetChatSessionsBySessionIdTracesPath = z.object({
    sessionId: z.string().min(1)
});

export const zGetChatSessionsBySessionIdRunSnapshotsPath = z.object({
    sessionId: z.string().min(1)
});

export const zPostChatSessionsBySessionIdCancelPath = z.object({
    sessionId: z.string().min(1)
});

export const zPostChatSessionsBySessionIdPermissionModeBody = z.object({
    mode: z.enum(['bypassPermissions', 'plan'])
});

export const zPostChatSessionsBySessionIdPermissionModePath = z.object({
    sessionId: z.string().min(1)
});

export const zPutChronicleConfigBody = z.object({
    profileId: z.string(),
    modelId: z.string(),
    workspaceId: z.string(),
    enabled: z.boolean(),
    activityPipelineEnabled: z.boolean(),
    activityPipelineIntervalMs: z.number(),
    activityPipelineBatchSize: z.number(),
    dreamSchedulerEnabled: z.boolean().optional().default(true),
    dreamSchedulerIntervalMs: z.number().optional().default(86400000),
    dreamSchedulerApplyMerge: z.boolean().optional().default(false),
    audioCaptureEnabled: z.boolean(),
    audioSource: z.enum([
        'microphone',
        'system',
        'mixed'
    ]).optional(),
    audioSegmentMs: z.number(),
    audioSegmentIntervalMs: z.number(),
    audioRmsThreshold: z.number(),
    storageRoot: z.string(),
    privacySensitiveAppBundleIds: z.array(z.string()).optional().default([]),
    privacySensitiveTitlePatterns: z.array(z.string()).optional().default([]),
    privacySensitiveUrlPatterns: z.array(z.string()).optional().default([]),
    closedEyesDiscardEnabled: z.boolean().optional().default(false),
    closedEyesMode: z.enum([
        'auto',
        'always-record',
        'always-pause'
    ]).optional()
});

export const zPostChronicleSummarizeBody = z.object({
    prompt: z.string().min(1),
    windowType: z.enum(['10min', '6h']),
    sourceSnapshotIds: z.array(z.string()).optional(),
    sourceArtifactPaths: z.array(z.string()).optional()
});

export const zPostChronicleSnapshotsBody = z.object({
    sourceId: z.string().min(1),
    displayId: z.number(),
    frameIndex: z.number().optional(),
    capturedAt: z.string().min(1),
    segmentDir: z.string(),
    framePath: z.string(),
    capturePath: z.string().optional(),
    ocrPath: z.string().optional(),
    snapshotPath: z.string().optional(),
    ocrText: z.string().optional(),
    appBundleId: z.string().optional(),
    windowTitle: z.string().optional(),
    closedEyes: z.object({
        status: z.enum([
            'open',
            'closed',
            'absent',
            'unknown'
        ]).optional(),
        confidence: z.number().gte(0).lte(1).nullish(),
        detector: z.string().nullish(),
        discard: z.boolean().optional(),
        reason: z.string().nullish(),
        metadata: z.record(z.string(), z.unknown()).optional()
    }).optional(),
    accessibility: z.object({
        sourceId: z.string().min(1),
        status: z.enum([
            'ready',
            'permission-denied',
            'unavailable',
            'error'
        ]).optional(),
        provider: z.string().optional(),
        accessibilityPath: z.string().nullish(),
        text: z.string().nullish(),
        elementCount: z.number().gte(0).optional(),
        appBundleId: z.string().nullish(),
        windowTitle: z.string().nullish(),
        tree: z.array(z.unknown()).optional(),
        metadata: z.record(z.string(), z.unknown()).optional()
    }).optional(),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zGetChronicleMemoriesQuery = z.object({
    limit: z.number().optional().default(20)
});

export const zPostChronicleMemoriesBody = z.object({
    sourceId: z.string().min(1),
    windowType: z.enum(['10min', '6h']),
    createdAt: z.string().min(1),
    memoryPath: z.string().optional(),
    content: z.string(),
    summaryKind: z.enum([
        'llm',
        'local',
        'imported'
    ]),
    sourceSnapshotPaths: z.array(z.string()).optional(),
    sourceFramePaths: z.array(z.string()).optional(),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zPostChronicleModelResourcesByCategoryVerifyPath = z.object({
    category: z.enum([
        'ocr',
        'audio-vad',
        'audio-asr',
        'speaker',
        'embedding',
        'pii'
    ])
});

export const zPostChronicleModelResourcesByCategoryInstallBody = z.object({
    source: z.enum(['manifest', 'local-files']).optional(),
    sourceRoot: z.string().nullish(),
    files: z.array(z.object({
        relativePath: z.string().min(1),
        sourcePath: z.string().min(1)
    })).optional()
});

export const zPostChronicleModelResourcesByCategoryInstallPath = z.object({
    category: z.enum([
        'ocr',
        'audio-vad',
        'audio-asr',
        'speaker',
        'embedding',
        'pii'
    ])
});

export const zDeleteChronicleModelResourcesByCategoryPath = z.object({
    category: z.enum([
        'ocr',
        'audio-vad',
        'audio-asr',
        'speaker',
        'embedding',
        'pii'
    ])
});

export const zPostChronicleMessageSourcesBody = z.object({
    platform: z.string(),
    label: z.string().min(1),
    enabled: z.boolean(),
    workspaceId: z.string().nullish(),
    teamId: z.string().nullish(),
    botTokenRef: z.string().nullish(),
    channelIds: z.array(z.string()),
    realtimeMode: z.enum(['polling', 'events-api']).optional(),
    signingSecretRef: z.string().nullish()
});

export const zDeleteChronicleMessageSourcesBySourceIdPath = z.object({
    sourceId: z.string().min(1)
});

export const zPatchChronicleMessageSourcesBySourceIdBody = z.object({
    label: z.string().min(1).optional(),
    enabled: z.boolean().optional(),
    workspaceId: z.string().nullish(),
    teamId: z.string().nullish(),
    botTokenRef: z.string().nullish(),
    channelIds: z.array(z.string()).optional(),
    realtimeMode: z.enum(['polling', 'events-api']).optional(),
    signingSecretRef: z.string().nullish()
});

export const zPatchChronicleMessageSourcesBySourceIdPath = z.object({
    sourceId: z.string().min(1)
});

export const zPostChronicleMessageSourcesBySourceIdSyncPath = z.object({
    sourceId: z.string().min(1)
});

export const zPostChronicleMessageSourcesBySourceIdSlackEventsPath = z.object({
    sourceId: z.string().min(1)
});

export const zGetChronicleMessagesQuery = z.object({
    limit: z.number().optional().default(50)
});

export const zGetChronicleAudioTranscriptsQuery = z.object({
    limit: z.number().optional().default(20)
});

export const zPostChronicleAudioTranscriptsBody = z.object({
    sourceId: z.string().min(1),
    title: z.string().nullish(),
    source: z.enum([
        'asr',
        'manual',
        'imported'
    ]).optional(),
    status: z.enum([
        'recording',
        'completed',
        'imported',
        'error'
    ]).optional(),
    startedAt: z.string().min(1),
    endedAt: z.string().nullish(),
    language: z.string().nullish(),
    appBundleId: z.string().nullish(),
    windowTitle: z.string().nullish(),
    audioPath: z.string().nullish(),
    transcriptPath: z.string().nullish(),
    segments: z.array(z.object({
        startMs: z.number().gte(0),
        endMs: z.number().gte(0).nullish(),
        speakerLabel: z.string().nullish(),
        text: z.string().min(1),
        confidence: z.number().gte(0).lte(1).nullish(),
        language: z.string().nullish(),
        metadata: z.record(z.string(), z.unknown()).optional()
    })),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zPostChronicleSpeakerProfilesBody = z.object({
    displayName: z.string().min(1),
    aliases: z.array(z.string()).optional(),
    embedding: z.array(z.number()).nullish(),
    embeddingModelId: z.string().nullish(),
    sampleCount: z.number().gte(0).optional(),
    lastSeenAt: z.string().nullish(),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zGetChronicleAudioRawSegmentsQuery = z.object({
    limit: z.number().optional().default(20)
});

export const zPostChronicleAudioRawSegmentsBody = z.object({
    sourceId: z.string().min(1),
    recordedAt: z.string().min(1),
    source: z.enum([
        'microphone',
        'system',
        'mixed'
    ]).optional(),
    status: z.enum([
        'captured',
        'queued',
        'processed',
        'ignored',
        'error'
    ]).optional(),
    audioPath: z.string().min(1),
    metadataPath: z.string().min(1),
    sampleRate: z.number().gte(1),
    channels: z.number().gte(1),
    sampleCount: z.number().gte(0),
    droppedSamples: z.number().gte(0).optional(),
    durationMs: z.number().gte(0).optional(),
    rms: z.number().gte(0).lte(1),
    peak: z.number().gte(0).lte(1),
    active: z.boolean(),
    vadImplemented: z.boolean().optional(),
    asrImplemented: z.boolean().optional(),
    speakerLabelingImplemented: z.boolean().optional(),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zPostChronicleAudioRawSegmentsBySourceIdProcessingResultBody = z.object({
    status: z.enum([
        'captured',
        'queued',
        'processed',
        'ignored',
        'error'
    ]).optional(),
    vadStatus: z.enum([
        'not-implemented',
        'pending',
        'ready',
        'error'
    ]).optional(),
    asrStatus: z.enum([
        'not-implemented',
        'pending',
        'ready',
        'error'
    ]).optional(),
    speakerStatus: z.enum([
        'not-implemented',
        'pending',
        'ready',
        'error'
    ]).optional(),
    transcriptSourceId: z.string().nullish(),
    speakerProfileIds: z.array(z.string()).optional(),
    errorMessage: z.string().nullish(),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zPostChronicleAudioRawSegmentsBySourceIdProcessingResultPath = z.object({
    sourceId: z.string().min(1)
});

export const zGetChronicleAccessibilitySnapshotsQuery = z.object({
    limit: z.number().optional().default(20)
});

export const zGetChronicleAccessibilityEventsQuery = z.object({
    limit: z.number().optional().default(50)
});

export const zPostChronicleAccessibilityEventsBody = z.object({
    sourceId: z.string().min(1),
    capturedAt: z.string().min(1),
    provider: z.string().optional(),
    appBundleId: z.string().nullish(),
    pid: z.number().nullish(),
    notification: z.string().min(1),
    droppedBefore: z.number().gte(0).optional(),
    snapshotId: z.string().nullish(),
    accessibilitySnapshotId: z.string().nullish(),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zGetChronicleActivitySegmentsQuery = z.object({
    limit: z.number().optional().default(20)
});

export const zGetChronicleActivitySegmentsBySegmentIdPath = z.object({
    segmentId: z.string().min(1)
});

export const zPostChronicleActivitySegmentsBySegmentIdTriagePath = z.object({
    segmentId: z.string().min(1)
});

export const zPostChronicleActivitySegmentsBySegmentIdSummarizePath = z.object({
    segmentId: z.string().min(1)
});

export const zPostChronicleActivitySegmentsBySegmentIdCrystallizePath = z.object({
    segmentId: z.string().min(1)
});

export const zGetChroniclePipelineRunsQuery = z.object({
    limit: z.number().optional().default(20)
});

export const zGetChronicleKnowledgeCardsQuery = z.object({
    limit: z.number().optional().default(50),
    dimension: z.enum([
        'technical',
        'business',
        'personal',
        'project',
        'general'
    ]).optional(),
    type: z.enum([
        'fact',
        'insight',
        'decision',
        'task',
        'pattern'
    ]).optional(),
    includeDeleted: z.boolean().optional().default(false)
});

export const zPostChronicleKnowledgeCardsBody = z.object({
    title: z.string().min(1),
    content: z.string().min(1),
    cardType: z.enum([
        'fact',
        'insight',
        'decision',
        'task',
        'pattern'
    ]).optional(),
    dimension: z.enum([
        'technical',
        'business',
        'personal',
        'project',
        'general'
    ]).optional(),
    confidence: z.number().gte(0).lte(1).optional(),
    sourceMemoryIds: z.array(z.string()).optional(),
    sourceSegmentIds: z.array(z.string()).optional(),
    sourceChunkIds: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
    stableKey: z.string().optional(),
    pinned: z.boolean().optional(),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zGetChronicleKnowledgeCardsByKnowledgeIdVersionsPath = z.object({
    knowledgeId: z.string().min(1)
});

export const zGetChronicleKnowledgeCardsByKnowledgeIdFilesPath = z.object({
    knowledgeId: z.string().min(1)
});

export const zPostChronicleKnowledgeCardsByKnowledgeIdVersionsRestoreBody = z.object({
    version: z.number().gte(1)
});

export const zPostChronicleKnowledgeCardsByKnowledgeIdVersionsRestorePath = z.object({
    knowledgeId: z.string().min(1)
});

export const zDeleteChronicleKnowledgeCardsByKnowledgeIdPath = z.object({
    knowledgeId: z.string().min(1)
});

export const zGetChronicleKnowledgeCardsByKnowledgeIdPath = z.object({
    knowledgeId: z.string().min(1)
});

export const zPatchChronicleKnowledgeCardsByKnowledgeIdBody = z.object({
    title: z.string().min(1).optional(),
    content: z.string().min(1).optional(),
    cardType: z.enum([
        'fact',
        'insight',
        'decision',
        'task',
        'pattern'
    ]).optional(),
    dimension: z.enum([
        'technical',
        'business',
        'personal',
        'project',
        'general'
    ]).optional(),
    confidence: z.number().gte(0).lte(1).optional(),
    sourceMemoryIds: z.array(z.string()).optional(),
    sourceSegmentIds: z.array(z.string()).optional(),
    sourceChunkIds: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
    pinned: z.boolean().optional(),
    status: z.enum([
        'active',
        'merged',
        'archived',
        'deleted'
    ]).optional(),
    mergedIntoId: z.string().nullish(),
    metadata: z.record(z.string(), z.unknown()).optional()
});

export const zPatchChronicleKnowledgeCardsByKnowledgeIdPath = z.object({
    knowledgeId: z.string().min(1)
});

export const zGetChronicleDreamRunsQuery = z.object({
    limit: z.number().optional().default(20)
});

export const zPostChronicleDreamRunsBody = z.object({
    runType: z.enum([
        'archive',
        'merge',
        'prune',
        'restore',
        'dry-run'
    ]).optional(),
    dryRun: z.boolean().optional(),
    limit: z.number().gte(2).optional(),
    similarityThreshold: z.number().gte(0.1).lte(1).optional(),
    applyMerge: z.boolean().optional(),
    olderThanDays: z.number().gte(0).optional(),
    knowledgeIds: z.array(z.string()).optional()
});

export const zGetChronicleTimelineQuery = z.object({
    limit: z.number().optional().default(50)
});

export const zGetChronicleEventsQuery = z.object({
    limit: z.number().gte(1).lte(500).optional().default(50),
    after: z.number().gte(0).optional()
});

export const zGetChronicleEventsStreamQuery = z.object({
    limit: z.number().gte(1).lte(500).optional().default(50),
    after: z.number().gte(0).optional(),
    intervalMs: z.number().gte(250).lte(30000).optional().default(1000),
    once: z.boolean().optional().default(false)
});

export const zGetChronicleSnapshotsBySnapshotIdFramePath = z.object({
    snapshotId: z.string()
});

export const zGetChronicleFrameByDisplayIdBySegmentByFramePath = z.object({
    displayId: z.string(),
    segment: z.string(),
    frame: z.string()
});

export const zGetChronicleMemoriesSearchQuery = z.object({
    q: z.string().min(1),
    limit: z.number().optional().default(20)
});

export const zDeleteChronicleMemoriesByMemoryIdPath = z.object({
    memoryId: z.string().min(1)
});

export const zGetChronicleMemoriesByMemoryIdPath = z.object({
    memoryId: z.string().min(1)
});

export const zPatchChronicleMemoriesByMemoryIdBody = z.object({
    content: z.string().min(1).optional(),
    metadata: z.record(z.string(), z.unknown()).optional(),
    sourceSnapshotPaths: z.array(z.string()).optional(),
    sourceFramePaths: z.array(z.string()).optional()
});

export const zPatchChronicleMemoriesByMemoryIdPath = z.object({
    memoryId: z.string().min(1)
});

export const zPostChroniclePrivacyRedactBody = z.object({
    text: z.string()
});

export const zPostChroniclePrivacyExportBody = z.object({
    workspaceId: z.string().nullish(),
    limit: z.number().gte(1).optional(),
    includeMemories: z.boolean().optional(),
    includeMessages: z.boolean().optional(),
    includeAudioTranscripts: z.boolean().optional(),
    includeSnapshots: z.boolean().optional(),
    outputFormat: z.enum(['markdown', 'json']).optional()
});

export const zPostChroniclePrivacySnapshotsBySnapshotIdFrameMaskBody = z.object({
    mode: z.string().optional(),
    fullFrame: z.boolean().optional(),
    blurSigma: z.number().gte(1).lte(100).optional(),
    regions: z.array(z.object({
        x: z.number().gte(0),
        y: z.number().gte(0),
        width: z.number().gte(1),
        height: z.number().gte(1)
    })).optional()
});

export const zPostChroniclePrivacySnapshotsBySnapshotIdFrameMaskPath = z.object({
    snapshotId: z.string().min(1)
});

export const zGetChroniclePrivacyBreadcrumbsQuery = z.object({
    limit: z.number().optional().default(50)
});

export const zPostChronicleEmbeddingsBody = z.object({
    texts: z.array(z.string().min(1)).min(1).max(64)
});

export const zGetApiActivitySessionsQuery = z.object({
    limit: z.number().gte(1).lte(200).optional().default(20)
});

export const zGetApiActivitySessionByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetApiActivitySessionByIdSnapshotsPath = z.object({
    id: z.string().min(1)
});

export const zGetApiActivitySnapshotByIdPath = z.object({
    id: z.string().min(1)
});

export const zGetApiActivitySnapshotByIdOcrPath = z.object({
    id: z.string().min(1)
});

export const zPostApiMemoryCrystallizeBody = z.object({
    segmentId: z.string().min(1).optional()
});

export const zPostTerminalSessionsBySessionIdStartOrAttachBody = z.object({
    cols: z.union([
        z.string(),
        z.int().gte(1)
    ]),
    rows: z.union([
        z.string(),
        z.int().gte(1)
    ])
});

export const zPostTerminalSessionsBySessionIdStartOrAttachPath = z.object({
    sessionId: z.string().min(1)
});

export const zDeleteTerminalSessionsBySessionIdPath = z.object({
    sessionId: z.string().min(1)
});

export const zPostTerminalSessionsShellStartBody = z.object({
    ptyId: z.string().min(1),
    cwd: z.string().min(1),
    cols: z.union([
        z.string(),
        z.int().gte(1)
    ]),
    rows: z.union([
        z.string(),
        z.int().gte(1)
    ])
});

export const zDeleteTerminalSessionsShellByPtyIdPath = z.object({
    ptyId: z.string().min(1)
});

export const zGetObservabilityEventsQuery = z.object({
    chatSessionId: z.string().optional(),
    runId: z.string().optional(),
    code: z.string().optional(),
    severity: z.string().optional(),
    since: z.string().optional(),
    until: z.string().optional(),
    limit: z.string().optional()
});

export const zPostObservabilityEventsBody = z.object({
    source: z.string(),
    code: z.string(),
    severity: z.string(),
    category: z.string(),
    message: z.string(),
    attrs: z.record(z.string(), z.unknown()).optional(),
    chatSessionId: z.string().optional(),
    runId: z.string().optional(),
    messageId: z.string().optional(),
    traceId: z.string().optional(),
    dedupeKey: z.string().optional(),
    parentEventId: z.string().optional(),
    occurredAt: z.number().optional(),
    recordedAt: z.number().optional()
});

export const zGetObservabilityIncidentsQuery = z.object({
    dedupeKey: z.string().optional(),
    chatSessionId: z.string().optional(),
    runId: z.string().optional(),
    code: z.string().optional(),
    status: z.enum(['open', 'resolved']).optional(),
    limit: z.string().optional()
});

export const zGetObservabilityErrorPatternsQuery = z.object({
    chatSessionId: z.string().optional(),
    runId: z.string().optional(),
    code: z.string().optional(),
    runtimeKind: z.string().optional(),
    providerTargetId: z.string().optional(),
    sinceUnix: z.string().optional(),
    limit: z.string().optional()
});

export const zGetObservabilityExportQuery = z.object({
    chatSessionId: z.string().optional(),
    runId: z.string().optional(),
    sinceUnix: z.string().optional()
});

export const zDeleteIssuesByIdDelegationPath = z.object({
    id: z.string()
});

export const zGetIssuesByIdDelegationPath = z.object({
    id: z.string()
});

export const zPostIssuesByIdDelegationBody = z.object({
    agentId: z.string().min(1),
    providerTargetId: z.string().nullish()
});

export const zPostIssuesByIdDelegationPath = z.object({
    id: z.string()
});

export const zGetIssuesByIdAgentSessionsPath = z.object({
    id: z.string()
});

export const zGetIssueAgentSessionsByAgentSessionIdActivitiesPath = z.object({
    agentSessionId: z.string()
});

export const zPostIssueAgentSessionsByAgentSessionIdContinuationBody = z.object({
    mode: z.enum(['queue', 'steer']),
    text: z.string().min(1)
});

export const zPostIssueAgentSessionsByAgentSessionIdContinuationPath = z.object({
    agentSessionId: z.string()
});

export const zPostIssueAgentSessionsByAgentSessionIdRerunBody = z.record(z.string(), z.unknown());

export const zPostIssueAgentSessionsByAgentSessionIdRerunPath = z.object({
    agentSessionId: z.string()
});

export const zDeleteIssueAgentSessionsByAgentSessionIdPath = z.object({
    agentSessionId: z.string()
});
