/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewChatRouteImport } from './routes/new-chat'
import { Route as DevtoolRouteImport } from './routes/devtool'
import { Route as KanbanRouteRouteImport } from './routes/kanban/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace.$workspaceId'
import { Route as ChatSessionIdRouteImport } from './routes/chat.$sessionId'
import { Route as KanbanBoardIdRouteRouteImport } from './routes/kanban/$boardId/route'
import { Route as KanbanBoardIdIndexRouteImport } from './routes/kanban/$boardId/index'
import { Route as KanbanBoardIdIssueIdRouteRouteImport } from './routes/kanban/$boardId/$issueId/route'

const UsageLazyRouteImport = createFileRoute('/usage')()

const UsageLazyRoute = UsageLazyRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/usage.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewChatRoute = NewChatRouteImport.update({
  id: '/new-chat',
  path: '/new-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolRoute = DevtoolRouteImport.update({
  id: '/devtool',
  path: '/devtool',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRouteRoute = KanbanRouteRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kanban.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/workspace.$workspaceId.lazy').then((d) => d.Route),
)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chat.$sessionId.lazy').then((d) => d.Route),
)
const KanbanBoardIdRouteRoute = KanbanBoardIdRouteRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => KanbanRouteRoute,
} as any)
const KanbanBoardIdIndexRoute = KanbanBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KanbanBoardIdRouteRoute,
} as any)
const KanbanBoardIdIssueIdRouteRoute =
  KanbanBoardIdIssueIdRouteRouteImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => KanbanBoardIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kanban': typeof KanbanRouteRouteWithChildren
  '/devtool': typeof DevtoolRoute
  '/new-chat': typeof NewChatRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageLazyRoute
  '/kanban/$boardId': typeof KanbanBoardIdRouteRouteWithChildren
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/kanban/$boardId/$issueId': typeof KanbanBoardIdIssueIdRouteRoute
  '/kanban/$boardId/': typeof KanbanBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kanban': typeof KanbanRouteRouteWithChildren
  '/devtool': typeof DevtoolRoute
  '/new-chat': typeof NewChatRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageLazyRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/kanban/$boardId/$issueId': typeof KanbanBoardIdIssueIdRouteRoute
  '/kanban/$boardId': typeof KanbanBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kanban': typeof KanbanRouteRouteWithChildren
  '/devtool': typeof DevtoolRoute
  '/new-chat': typeof NewChatRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageLazyRoute
  '/kanban/$boardId': typeof KanbanBoardIdRouteRouteWithChildren
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/kanban/$boardId/$issueId': typeof KanbanBoardIdIssueIdRouteRoute
  '/kanban/$boardId/': typeof KanbanBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kanban'
    | '/devtool'
    | '/new-chat'
    | '/settings'
    | '/usage'
    | '/kanban/$boardId'
    | '/chat/$sessionId'
    | '/workspace/$workspaceId'
    | '/kanban/$boardId/$issueId'
    | '/kanban/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kanban'
    | '/devtool'
    | '/new-chat'
    | '/settings'
    | '/usage'
    | '/chat/$sessionId'
    | '/workspace/$workspaceId'
    | '/kanban/$boardId/$issueId'
    | '/kanban/$boardId'
  id:
    | '__root__'
    | '/'
    | '/kanban'
    | '/devtool'
    | '/new-chat'
    | '/settings'
    | '/usage'
    | '/kanban/$boardId'
    | '/chat/$sessionId'
    | '/workspace/$workspaceId'
    | '/kanban/$boardId/$issueId'
    | '/kanban/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KanbanRouteRoute: typeof KanbanRouteRouteWithChildren
  DevtoolRoute: typeof DevtoolRoute
  NewChatRoute: typeof NewChatRoute
  SettingsRoute: typeof SettingsRoute
  UsageLazyRoute: typeof UsageLazyRoute
  ChatSessionIdRoute: typeof ChatSessionIdRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-chat': {
      id: '/new-chat'
      path: '/new-chat'
      fullPath: '/new-chat'
      preLoaderRoute: typeof NewChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtool': {
      id: '/devtool'
      path: '/devtool'
      fullPath: '/devtool'
      preLoaderRoute: typeof DevtoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban/$boardId': {
      id: '/kanban/$boardId'
      path: '/$boardId'
      fullPath: '/kanban/$boardId'
      preLoaderRoute: typeof KanbanBoardIdRouteRouteImport
      parentRoute: typeof KanbanRouteRoute
    }
    '/kanban/$boardId/': {
      id: '/kanban/$boardId/'
      path: '/'
      fullPath: '/kanban/$boardId/'
      preLoaderRoute: typeof KanbanBoardIdIndexRouteImport
      parentRoute: typeof KanbanBoardIdRouteRoute
    }
    '/kanban/$boardId/$issueId': {
      id: '/kanban/$boardId/$issueId'
      path: '/$issueId'
      fullPath: '/kanban/$boardId/$issueId'
      preLoaderRoute: typeof KanbanBoardIdIssueIdRouteRouteImport
      parentRoute: typeof KanbanBoardIdRouteRoute
    }
  }
}

interface KanbanBoardIdRouteRouteChildren {
  KanbanBoardIdIssueIdRouteRoute: typeof KanbanBoardIdIssueIdRouteRoute
  KanbanBoardIdIndexRoute: typeof KanbanBoardIdIndexRoute
}

const KanbanBoardIdRouteRouteChildren: KanbanBoardIdRouteRouteChildren = {
  KanbanBoardIdIssueIdRouteRoute: KanbanBoardIdIssueIdRouteRoute,
  KanbanBoardIdIndexRoute: KanbanBoardIdIndexRoute,
}

const KanbanBoardIdRouteRouteWithChildren =
  KanbanBoardIdRouteRoute._addFileChildren(KanbanBoardIdRouteRouteChildren)

interface KanbanRouteRouteChildren {
  KanbanBoardIdRouteRoute: typeof KanbanBoardIdRouteRouteWithChildren
}

const KanbanRouteRouteChildren: KanbanRouteRouteChildren = {
  KanbanBoardIdRouteRoute: KanbanBoardIdRouteRouteWithChildren,
}

const KanbanRouteRouteWithChildren = KanbanRouteRoute._addFileChildren(
  KanbanRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KanbanRouteRoute: KanbanRouteRouteWithChildren,
  DevtoolRoute: DevtoolRoute,
  NewChatRoute: NewChatRoute,
  SettingsRoute: SettingsRoute,
  UsageLazyRoute: UsageLazyRoute,
  ChatSessionIdRoute: ChatSessionIdRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
