import { t } from 'elysia'

const thinkingEffortEnum = t.Union([
  t.Literal('low'),
  t.Literal('medium'),
  t.Literal('high'),
  t.Literal('auto'),
])

const runtimeKindEnum = t.Union([
  t.Literal('standard'),
  t.Literal('claude-agent'),
  t.Literal('codex'),
  t.Literal('jar-core'),
  t.Literal('acp-chat'),
  t.Literal('cli-tui'),
])

const importCandidateSourceKindEnum = t.Union([
  t.Literal('cc-switch'),
  t.Literal('local-config'),
])

const importedRuntimeKindEnum = t.Union([
  t.Literal('claude-agent'),
  t.Literal('codex'),
])

const importAppEnum = t.Union([
  t.Literal('claude'),
  t.Literal('codex'),
])

const importSourceRefresh = t.Object({
  sourceKey: t.String(),
  sourceLabel: t.String(),
  status: t.Union([t.Literal('ok'), t.Literal('warning'), t.Literal('error')]),
  recordsSeen: t.Number(),
  recordsProjected: t.Number(),
  recordsMissing: t.Number(),
  message: t.Nullable(t.String()),
})

export const AgentIdentityModel = {
  agent: t.Object({
    id: t.String(),
    name: t.String(),
    description: t.Nullable(t.String()),
    avatarUrl: t.Nullable(t.String()),
    avatarStyle: t.String(),
    avatarSeed: t.String(),
    providerTargetId: t.Nullable(t.String()),
    modelId: t.Nullable(t.String()),
    thinkingEffort: thinkingEffortEnum,
    runtimeKind: runtimeKindEnum,
    configJson: t.String(),
    enabled: t.Boolean(),
    createdAt: t.Number(),
    updatedAt: t.Number(),
  }),

  idParams: t.Object({
    id: t.String({ minLength: 1 }),
  }),

  listQuery: t.Object({
    enabled: t.Optional(t.String()),
    providerTargetId: t.Optional(t.String()),
  }),

  createBody: t.Object({
    name: t.String({ minLength: 1 }),
    description: t.Optional(t.Nullable(t.String())),
    avatarStyle: t.String({ minLength: 1 }),
    avatarSeed: t.String({ minLength: 1 }),
    providerTargetId: t.Optional(t.Nullable(t.String())),
    modelId: t.Optional(t.Nullable(t.String())),
    thinkingEffort: t.Optional(thinkingEffortEnum),
    runtimeKind: t.Optional(runtimeKindEnum),
    configJson: t.Optional(t.String()),
  }),

  updateBody: t.Object({
    name: t.Optional(t.String({ minLength: 1 })),
    description: t.Optional(t.Nullable(t.String())),
    avatarStyle: t.Optional(t.String({ minLength: 1 })),
    avatarSeed: t.Optional(t.String({ minLength: 1 })),
    providerTargetId: t.Optional(t.Nullable(t.String())),
    modelId: t.Optional(t.Nullable(t.String())),
    thinkingEffort: t.Optional(thinkingEffortEnum),
    runtimeKind: t.Optional(runtimeKindEnum),
    configJson: t.Optional(t.String()),
    enabled: t.Optional(t.Boolean()),
  }),

  importLocalConfigBody: t.Optional(t.Object({
    includeProcessEnv: t.Optional(t.Boolean()),
    candidateIds: t.Optional(t.Array(t.String({ minLength: 1 }))),
  })),

  localConfigImportCandidate: t.Object({
    id: t.String(),
    app: importAppEnum,
    runtimeKind: importedRuntimeKindEnum,
    sourceKind: importCandidateSourceKindEnum,
    sourceLabel: t.String(),
    externalRecordId: t.String(),
    providerTargetId: t.Nullable(t.String()),
    agentName: t.String(),
    resolvedProviderName: t.String(),
    name: t.String(),
    modelId: t.Nullable(t.String()),
    endpoint: t.Nullable(t.String()),
    importable: t.Boolean(),
    alreadyConfigured: t.Boolean(),
    reason: t.Nullable(t.String()),
    notes: t.Array(t.String()),
    agent: t.Nullable(t.Object({
      id: t.String(),
      name: t.String(),
      description: t.Nullable(t.String()),
      avatarUrl: t.Nullable(t.String()),
      avatarStyle: t.String(),
      avatarSeed: t.String(),
      providerTargetId: t.Nullable(t.String()),
      modelId: t.Nullable(t.String()),
      thinkingEffort: thinkingEffortEnum,
      runtimeKind: runtimeKindEnum,
      configJson: t.String(),
      enabled: t.Boolean(),
      createdAt: t.Number(),
      updatedAt: t.Number(),
    })),
  }),

  previewLocalConfigImportResult: t.Object({
    candidates: t.Array(t.Object({
      id: t.String(),
      app: importAppEnum,
      runtimeKind: importedRuntimeKindEnum,
      sourceKind: importCandidateSourceKindEnum,
      sourceLabel: t.String(),
      externalRecordId: t.String(),
      providerTargetId: t.Nullable(t.String()),
      agentName: t.String(),
      resolvedProviderName: t.String(),
      name: t.String(),
      modelId: t.Nullable(t.String()),
      endpoint: t.Nullable(t.String()),
      importable: t.Boolean(),
      alreadyConfigured: t.Boolean(),
      reason: t.Nullable(t.String()),
      notes: t.Array(t.String()),
      agent: t.Nullable(t.Object({
        id: t.String(),
        name: t.String(),
        description: t.Nullable(t.String()),
        avatarUrl: t.Nullable(t.String()),
        avatarStyle: t.String(),
        avatarSeed: t.String(),
        providerTargetId: t.Nullable(t.String()),
        modelId: t.Nullable(t.String()),
        thinkingEffort: thinkingEffortEnum,
        runtimeKind: runtimeKindEnum,
        configJson: t.String(),
        enabled: t.Boolean(),
        createdAt: t.Number(),
        updatedAt: t.Number(),
      })),
    })),
    sourceRefreshes: t.Array(importSourceRefresh),
  }),

  importLocalConfigResult: t.Object({
    preview: t.Object({
      candidates: t.Array(t.Object({
        id: t.String(),
        app: importAppEnum,
        runtimeKind: importedRuntimeKindEnum,
        sourceKind: importCandidateSourceKindEnum,
        sourceLabel: t.String(),
        externalRecordId: t.String(),
        providerTargetId: t.Nullable(t.String()),
        agentName: t.String(),
        resolvedProviderName: t.String(),
        name: t.String(),
        modelId: t.Nullable(t.String()),
        endpoint: t.Nullable(t.String()),
        importable: t.Boolean(),
        alreadyConfigured: t.Boolean(),
        reason: t.Nullable(t.String()),
        notes: t.Array(t.String()),
        agent: t.Nullable(t.Object({
          id: t.String(),
          name: t.String(),
          description: t.Nullable(t.String()),
          avatarUrl: t.Nullable(t.String()),
          avatarStyle: t.String(),
          avatarSeed: t.String(),
          providerTargetId: t.Nullable(t.String()),
          modelId: t.Nullable(t.String()),
          thinkingEffort: thinkingEffortEnum,
          runtimeKind: runtimeKindEnum,
          configJson: t.String(),
          enabled: t.Boolean(),
          createdAt: t.Number(),
          updatedAt: t.Number(),
        })),
      })),
      sourceRefreshes: t.Array(importSourceRefresh),
    }),
    created: t.Number(),
    existing: t.Number(),
    skipped: t.Number(),
    agents: t.Array(t.Object({
      app: importAppEnum,
      candidateId: t.String(),
      sourceKind: importCandidateSourceKindEnum,
      externalRecordId: t.String(),
      providerTargetId: t.Nullable(t.String()),
      runtimeKind: importedRuntimeKindEnum,
      status: t.Union([t.Literal('created'), t.Literal('existing'), t.Literal('skipped')]),
      reason: t.Nullable(t.String()),
      agent: t.Nullable(t.Object({
        id: t.String(),
        name: t.String(),
        description: t.Nullable(t.String()),
        avatarUrl: t.Nullable(t.String()),
        avatarStyle: t.String(),
        avatarSeed: t.String(),
        providerTargetId: t.Nullable(t.String()),
        modelId: t.Nullable(t.String()),
        thinkingEffort: thinkingEffortEnum,
        runtimeKind: runtimeKindEnum,
        configJson: t.String(),
        enabled: t.Boolean(),
        createdAt: t.Number(),
        updatedAt: t.Number(),
      })),
    })),
  }),
}
