CREATE INDEX `backend_runs_binding_id_idx` ON `backend_runs` (`binding_id`);--> statement-breakpoint
CREATE INDEX `backend_runs_chat_session_id_idx` ON `backend_runs` (`chat_session_id`);--> statement-breakpoint
CREATE INDEX `backend_runs_message_id_idx` ON `backend_runs` (`message_id`);--> statement-breakpoint
CREATE INDEX `backend_runs_started_at_idx` ON `backend_runs` (`started_at`);--> statement-breakpoint
CREATE INDEX `backend_session_bindings_agent_profile_id_idx` ON `backend_session_bindings` (`agent_profile_id`);--> statement-breakpoint
CREATE INDEX `backend_session_bindings_runtime_kind_idx` ON `backend_session_bindings` (`runtime_kind`);--> statement-breakpoint
CREATE INDEX `messages_session_id_idx` ON `messages` (`session_id`);--> statement-breakpoint
CREATE INDEX `messages_session_created_at_idx` ON `messages` (`session_id`,`created_at`);--> statement-breakpoint
CREATE INDEX `messages_parent_tool_call_id_idx` ON `messages` (`parent_tool_call_id`);--> statement-breakpoint
CREATE INDEX `sessions_workspace_id_idx` ON `sessions` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `sessions_agent_profile_id_idx` ON `sessions` (`agent_profile_id`);--> statement-breakpoint
CREATE INDEX `sessions_linked_issue_id_idx` ON `sessions` (`linked_issue_id`);--> statement-breakpoint
CREATE INDEX `step_usage_run_id_idx` ON `step_usage` (`run_id`);--> statement-breakpoint
CREATE INDEX `step_usage_session_id_idx` ON `step_usage` (`session_id`);--> statement-breakpoint
CREATE INDEX `usage_logs_session_id_idx` ON `usage_logs` (`session_id`);--> statement-breakpoint
CREATE INDEX `usage_logs_message_id_idx` ON `usage_logs` (`message_id`);--> statement-breakpoint
CREATE INDEX `usage_logs_agent_profile_id_idx` ON `usage_logs` (`agent_profile_id`);--> statement-breakpoint
CREATE INDEX `agent_activities_agent_session_id_idx` ON `agent_activities` (`agent_session_id`);--> statement-breakpoint
CREATE INDEX `agent_sessions_issue_id_idx` ON `agent_sessions` (`issue_id`);--> statement-breakpoint
CREATE INDEX `agent_sessions_agent_profile_id_idx` ON `agent_sessions` (`agent_profile_id`);--> statement-breakpoint
CREATE INDEX `agent_sessions_chat_session_id_idx` ON `agent_sessions` (`chat_session_id`);--> statement-breakpoint
CREATE INDEX `kanban_boards_workspace_id_idx` ON `kanban_boards` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `kanban_issue_comments_issue_id_idx` ON `kanban_issue_comments` (`issue_id`);--> statement-breakpoint
CREATE INDEX `kanban_issue_relations_source_issue_id_idx` ON `kanban_issue_relations` (`source_issue_id`);--> statement-breakpoint
CREATE INDEX `kanban_issue_relations_target_issue_id_idx` ON `kanban_issue_relations` (`target_issue_id`);--> statement-breakpoint
CREATE INDEX `kanban_issues_workspace_id_idx` ON `kanban_issues` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `kanban_issues_status_id_idx` ON `kanban_issues` (`status_id`);--> statement-breakpoint
CREATE INDEX `kanban_issues_milestone_id_idx` ON `kanban_issues` (`milestone_id`);--> statement-breakpoint
CREATE INDEX `kanban_issues_parent_issue_id_idx` ON `kanban_issues` (`parent_issue_id`);--> statement-breakpoint
CREATE INDEX `kanban_issues_delegate_agent_profile_id_idx` ON `kanban_issues` (`delegate_agent_profile_id`);--> statement-breakpoint
CREATE INDEX `kanban_milestones_workspace_id_idx` ON `kanban_milestones` (`workspace_id`);--> statement-breakpoint
CREATE INDEX `kanban_statuses_workspace_id_idx` ON `kanban_statuses` (`workspace_id`);