// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeConversationArchitecture } from "../RealtimeConversationArchitecture";
import type { RealtimeConversationVersion } from "../RealtimeConversationVersion";
import type { RealtimeOutputModality } from "../RealtimeOutputModality";
import type { RealtimeVoice } from "../RealtimeVoice";
import type { ThreadRealtimeStartTransport } from "./ThreadRealtimeStartTransport";

/**
 * EXPERIMENTAL - start a thread-scoped realtime session.
 */
export type ThreadRealtimeStartParams = { threadId: string,
/**
 * Overrides the configured realtime architecture for this session only.
 */
architecture?: RealtimeConversationArchitecture | null,
/**
 * Sends automatic Codex responses as realtime conversation items instead of handoff appends.
 */
codexResponsesAsItems?: boolean | null,
/**
 * Optional prefix added to automatic Codex response items when `codexResponsesAsItems` is true.
 */
codexResponseItemPrefix?: string | null,
/**
 * Overrides the configured realtime model for this session only.
 */
model?: string | null,
/**
 * Selects text or audio output for the realtime session. Transport and voice stay
 * independent so clients can choose how they connect separately from what the model emits.
 */
outputModality: RealtimeOutputModality,
/**
 * Set to false to start without Codex's startup context. Omitted or null includes it.
 */
includeStartupContext?: boolean | null, prompt?: string | null | null, realtimeSessionId?: string | null, transport?: ThreadRealtimeStartTransport | null,
/**
 * Overrides the configured realtime protocol version for this session only.
 */
version?: RealtimeConversationVersion | null, voice?: RealtimeVoice | null, };
