import { t } from 'elysia'

export const ChronicleModel = {
  config: t.Object({
    profileId: t.String(),
    modelId: t.String(),
    workspaceId: t.String(),
    enabled: t.Boolean(),
    activityPipelineEnabled: t.Boolean(),
    activityPipelineIntervalMs: t.Number(),
    activityPipelineBatchSize: t.Number(),
    audioCaptureEnabled: t.Boolean(),
    audioSegmentMs: t.Number(),
    audioSegmentIntervalMs: t.Number(),
    audioRmsThreshold: t.Number(),
    storageRoot: t.String(),
  }),

  timelineEntry: t.Object({
    id: t.String(),
    sourceType: t.Optional(t.Union([t.Literal('snapshot'), t.Literal('message'), t.Literal('audio')])),
    capturedAt: t.String(),
    capturedAtUnix: t.Number(),
    displayId: t.Number(),
    segmentDir: t.String(),
    framePath: t.String(),
    ocrText: t.Nullable(t.String()),
    appBundleId: t.Nullable(t.String()),
    windowTitle: t.Nullable(t.String()),
    platform: t.Optional(t.Nullable(t.String())),
    channelId: t.Optional(t.Nullable(t.String())),
    channelName: t.Optional(t.Nullable(t.String())),
    userName: t.Optional(t.Nullable(t.String())),
  }),

  memoryEntry: t.Object({
    id: t.String(),
    type: t.Union([t.Literal('10min'), t.Literal('6h')]),
    source: t.Union([t.Literal('llm'), t.Literal('local'), t.Literal('imported')]),
    createdAt: t.String(),
    createdAtUnix: t.Number(),
    content: t.String(),
    modelId: t.Nullable(t.String()),
    matchKind: t.Nullable(t.Union([t.Literal('keyword'), t.Literal('semantic'), t.Literal('hybrid')])),
    keywordScore: t.Nullable(t.Number()),
    semanticScore: t.Nullable(t.Number()),
  }),

  modelResource: t.Object({
    id: t.String(),
    category: t.Union([
      t.Literal('ocr'),
      t.Literal('audio-vad'),
      t.Literal('audio-asr'),
      t.Literal('speaker'),
      t.Literal('embedding'),
    ]),
    status: t.Union([
      t.Literal('available'),
      t.Literal('missing'),
      t.Literal('installing'),
      t.Literal('installed'),
      t.Literal('error'),
    ]),
    displayName: t.String(),
    path: t.Nullable(t.String()),
    version: t.Nullable(t.String()),
    message: t.Nullable(t.String()),
    sizeBytes: t.Nullable(t.Number()),
    metadata: t.Record(t.String(), t.Any()),
    updatedAt: t.Number(),
  }),

  modelResourceCategoryParams: t.Object({
    category: t.Union([
      t.Literal('ocr'),
      t.Literal('audio-vad'),
      t.Literal('audio-asr'),
      t.Literal('speaker'),
      t.Literal('embedding'),
    ]),
  }),

  modelResourceInstallBody: t.Object({
    source: t.Optional(t.Union([t.Literal('manifest'), t.Literal('local-files')])),
    sourceRoot: t.Optional(t.Nullable(t.String())),
    files: t.Optional(t.Array(t.Object({
      relativePath: t.String({ minLength: 1 }),
      sourcePath: t.String({ minLength: 1 }),
    }))),
  }),

  messageSource: t.Object({
    id: t.String(),
    platform: t.Literal('slack'),
    label: t.String(),
    enabled: t.Boolean(),
    workspaceId: t.Nullable(t.String()),
    teamId: t.Nullable(t.String()),
    botTokenRef: t.Nullable(t.String()),
    channelIds: t.Array(t.String()),
    realtimeMode: t.Union([
      t.Literal('polling'),
      t.Literal('events-api'),
      t.Literal('socket-mode'),
    ]),
    signingSecretRef: t.Nullable(t.String()),
    status: t.Union([
      t.Literal('idle'),
      t.Literal('syncing'),
      t.Literal('ready'),
      t.Literal('error'),
      t.Literal('disabled'),
    ]),
    lastSyncAt: t.Nullable(t.Number()),
    lastMessageAt: t.Nullable(t.Number()),
    lastError: t.Nullable(t.String()),
    createdAt: t.Number(),
    updatedAt: t.Number(),
  }),

  messageSourceBody: t.Object({
    platform: t.Literal('slack'),
    label: t.String({ minLength: 1 }),
    enabled: t.Boolean(),
    workspaceId: t.Optional(t.Nullable(t.String())),
    teamId: t.Optional(t.Nullable(t.String())),
    botTokenRef: t.Optional(t.Nullable(t.String())),
    channelIds: t.Array(t.String()),
    realtimeMode: t.Optional(t.Union([
      t.Literal('polling'),
      t.Literal('events-api'),
      t.Literal('socket-mode'),
    ])),
    signingSecretRef: t.Optional(t.Nullable(t.String())),
  }),

  messageSourcePatchBody: t.Object({
    label: t.Optional(t.String({ minLength: 1 })),
    enabled: t.Optional(t.Boolean()),
    workspaceId: t.Optional(t.Nullable(t.String())),
    teamId: t.Optional(t.Nullable(t.String())),
    botTokenRef: t.Optional(t.Nullable(t.String())),
    channelIds: t.Optional(t.Array(t.String())),
    realtimeMode: t.Optional(t.Union([
      t.Literal('polling'),
      t.Literal('events-api'),
      t.Literal('socket-mode'),
    ])),
    signingSecretRef: t.Optional(t.Nullable(t.String())),
  }),

  messageEntry: t.Object({
    id: t.String(),
    sourceId: t.String(),
    platform: t.Literal('slack'),
    channelId: t.String(),
    channelName: t.Nullable(t.String()),
    userName: t.Nullable(t.String()),
    text: t.String(),
    messageTs: t.String(),
    messageAt: t.String(),
    messageAtUnix: t.Number(),
    permalink: t.Nullable(t.String()),
  }),

  audioSegment: t.Object({
    id: t.String(),
    segmentIndex: t.Number(),
    startMs: t.Number(),
    endMs: t.Nullable(t.Number()),
    speakerLabel: t.Nullable(t.String()),
    text: t.String(),
    confidence: t.Nullable(t.Number()),
    language: t.Nullable(t.String()),
  }),

  audioTranscript: t.Object({
    id: t.String(),
    sourceId: t.String(),
    memoryId: t.Nullable(t.String()),
    title: t.Nullable(t.String()),
    source: t.Union([t.Literal('asr'), t.Literal('manual'), t.Literal('imported')]),
    status: t.Union([t.Literal('recording'), t.Literal('completed'), t.Literal('imported'), t.Literal('error')]),
    startedAt: t.String(),
    startedAtUnix: t.Number(),
    endedAt: t.Nullable(t.String()),
    endedAtUnix: t.Nullable(t.Number()),
    language: t.Nullable(t.String()),
    appBundleId: t.Nullable(t.String()),
    windowTitle: t.Nullable(t.String()),
    segmentCount: t.Number(),
    previewText: t.String(),
    segments: t.Array(t.Object({
      id: t.String(),
      segmentIndex: t.Number(),
      startMs: t.Number(),
      endMs: t.Nullable(t.Number()),
      speakerLabel: t.Nullable(t.String()),
      text: t.String(),
      confidence: t.Nullable(t.Number()),
      language: t.Nullable(t.String()),
    })),
  }),

  audioTranscriptSegmentBody: t.Object({
    startMs: t.Number({ minimum: 0 }),
    endMs: t.Optional(t.Nullable(t.Number({ minimum: 0 }))),
    speakerLabel: t.Optional(t.Nullable(t.String())),
    text: t.String({ minLength: 1 }),
    confidence: t.Optional(t.Nullable(t.Number({ minimum: 0, maximum: 1 }))),
    language: t.Optional(t.Nullable(t.String())),
    metadata: t.Optional(t.Record(t.String(), t.Any())),
  }),

  audioTranscriptReportBody: t.Object({
    sourceId: t.String({ minLength: 1 }),
    title: t.Optional(t.Nullable(t.String())),
    source: t.Optional(t.Union([t.Literal('asr'), t.Literal('manual'), t.Literal('imported')])),
    status: t.Optional(t.Union([t.Literal('recording'), t.Literal('completed'), t.Literal('imported'), t.Literal('error')])),
    startedAt: t.String({ minLength: 1 }),
    endedAt: t.Optional(t.Nullable(t.String())),
    language: t.Optional(t.Nullable(t.String())),
    appBundleId: t.Optional(t.Nullable(t.String())),
    windowTitle: t.Optional(t.Nullable(t.String())),
    audioPath: t.Optional(t.Nullable(t.String())),
    transcriptPath: t.Optional(t.Nullable(t.String())),
    segments: t.Array(t.Object({
      startMs: t.Number({ minimum: 0 }),
      endMs: t.Optional(t.Nullable(t.Number({ minimum: 0 }))),
      speakerLabel: t.Optional(t.Nullable(t.String())),
      text: t.String({ minLength: 1 }),
      confidence: t.Optional(t.Nullable(t.Number({ minimum: 0, maximum: 1 }))),
      language: t.Optional(t.Nullable(t.String())),
      metadata: t.Optional(t.Record(t.String(), t.Any())),
    })),
    metadata: t.Optional(t.Record(t.String(), t.Any())),
  }),

  audioRawSegment: t.Object({
    id: t.String(),
    sourceId: t.String(),
    recordedAt: t.String(),
    recordedAtUnix: t.Number(),
    source: t.Union([t.Literal('microphone'), t.Literal('system'), t.Literal('mixed')]),
    status: t.Union([
      t.Literal('captured'),
      t.Literal('queued'),
      t.Literal('processed'),
      t.Literal('ignored'),
      t.Literal('error'),
    ]),
    audioPath: t.String(),
    metadataPath: t.String(),
    sampleRate: t.Number(),
    channels: t.Number(),
    sampleCount: t.Number(),
    droppedSamples: t.Number(),
    durationMs: t.Number(),
    rms: t.Number(),
    peak: t.Number(),
    active: t.Boolean(),
    vadStatus: t.Union([t.Literal('not-implemented'), t.Literal('pending'), t.Literal('ready'), t.Literal('error')]),
    asrStatus: t.Union([t.Literal('not-implemented'), t.Literal('pending'), t.Literal('ready'), t.Literal('error')]),
    speakerStatus: t.Union([t.Literal('not-implemented'), t.Literal('pending'), t.Literal('ready'), t.Literal('error')]),
    metadata: t.Record(t.String(), t.Any()),
  }),

  activitySegment: t.Object({
    id: t.String(),
    sessionId: t.String(),
    startedAt: t.String(),
    startedAtUnix: t.Number(),
    endedAt: t.String(),
    endedAtUnix: t.Number(),
    durationSeconds: t.Number(),
    segmentType: t.Union([
      t.Literal('work'),
      t.Literal('meeting'),
      t.Literal('browsing'),
      t.Literal('chat'),
      t.Literal('audio'),
      t.Literal('idle'),
      t.Literal('unknown'),
    ]),
    frontApp: t.Nullable(t.String()),
    title: t.Nullable(t.String()),
    summary: t.Nullable(t.String()),
    sourceCounts: t.Record(t.String(), t.Number()),
    sourceRefs: t.Record(t.String(), t.Array(t.String())),
    pipelineStatus: t.Union([
      t.Literal('collecting'),
      t.Literal('triaged'),
      t.Literal('summarized'),
      t.Literal('crystallized'),
      t.Literal('error'),
    ]),
    isCrystallized: t.Boolean(),
    metadata: t.Record(t.String(), t.Any()),
  }),

  pipelineRun: t.Object({
    id: t.String(),
    sessionId: t.Nullable(t.String()),
    segmentId: t.Nullable(t.String()),
    trigger: t.Union([
      t.Literal('snapshot'),
      t.Literal('message'),
      t.Literal('audio-raw'),
      t.Literal('audio-transcript'),
      t.Literal('memory'),
      t.Literal('manual'),
      t.Literal('summarize'),
    ]),
    stage: t.Union([
      t.Literal('collection'),
      t.Literal('segmentation'),
      t.Literal('triage'),
      t.Literal('summarization'),
      t.Literal('crystallization'),
    ]),
    status: t.Union([
      t.Literal('queued'),
      t.Literal('running'),
      t.Literal('success'),
      t.Literal('error'),
      t.Literal('skipped'),
    ]),
    startedAt: t.String(),
    startedAtUnix: t.Number(),
    endedAt: t.Nullable(t.String()),
    endedAtUnix: t.Nullable(t.Number()),
    errorMessage: t.Nullable(t.String()),
    snapshotsCount: t.Number(),
    messagesCount: t.Number(),
    audioTranscriptsCount: t.Number(),
    audioRawSegmentsCount: t.Number(),
    memoriesCount: t.Number(),
    segmentsCount: t.Number(),
    segmentIds: t.Array(t.String()),
    metadata: t.Record(t.String(), t.Any()),
  }),

  knowledgeCard: t.Object({
    id: t.String(),
    title: t.String(),
    content: t.String(),
    cardType: t.Union([
      t.Literal('fact'),
      t.Literal('insight'),
      t.Literal('decision'),
      t.Literal('task'),
      t.Literal('pattern'),
    ]),
    dimension: t.Union([
      t.Literal('technical'),
      t.Literal('business'),
      t.Literal('personal'),
      t.Literal('project'),
      t.Literal('general'),
    ]),
    confidence: t.Number(),
    sourceMemoryIds: t.Array(t.String()),
    sourceSegmentIds: t.Array(t.String()),
    sourceChunkIds: t.Array(t.String()),
    tags: t.Array(t.String()),
    contentHash: t.String(),
    version: t.Number(),
    status: t.Union([
      t.Literal('active'),
      t.Literal('merged'),
      t.Literal('archived'),
      t.Literal('deleted'),
    ]),
    mergedIntoId: t.Nullable(t.String()),
    pinned: t.Boolean(),
    metadata: t.Record(t.String(), t.Any()),
    createdAt: t.String(),
    createdAtUnix: t.Number(),
    updatedAt: t.String(),
    updatedAtUnix: t.Number(),
  }),

  knowledgeVersion: t.Object({
    id: t.String(),
    knowledgeId: t.String(),
    version: t.Number(),
    title: t.String(),
    content: t.String(),
    cardType: t.Union([
      t.Literal('fact'),
      t.Literal('insight'),
      t.Literal('decision'),
      t.Literal('task'),
      t.Literal('pattern'),
    ]),
    dimension: t.Union([
      t.Literal('technical'),
      t.Literal('business'),
      t.Literal('personal'),
      t.Literal('project'),
      t.Literal('general'),
    ]),
    confidence: t.Number(),
    sourceMemoryIds: t.Array(t.String()),
    sourceSegmentIds: t.Array(t.String()),
    sourceChunkIds: t.Array(t.String()),
    tags: t.Array(t.String()),
    metadata: t.Record(t.String(), t.Any()),
    createdAt: t.String(),
    createdAtUnix: t.Number(),
  }),

  dreamRun: t.Object({
    id: t.String(),
    workspaceId: t.Nullable(t.String()),
    runType: t.Union([
      t.Literal('archive'),
      t.Literal('merge'),
      t.Literal('prune'),
      t.Literal('restore'),
      t.Literal('dry-run'),
    ]),
    status: t.Union([
      t.Literal('running'),
      t.Literal('completed'),
      t.Literal('failed'),
    ]),
    startedAt: t.String(),
    startedAtUnix: t.Number(),
    endedAt: t.Nullable(t.String()),
    endedAtUnix: t.Nullable(t.Number()),
    inputCount: t.Number(),
    outputCount: t.Number(),
    mergedCount: t.Number(),
    deletedCount: t.Number(),
    sourceKnowledgeIds: t.Array(t.String()),
    outputKnowledgeIds: t.Array(t.String()),
    config: t.Record(t.String(), t.Any()),
    result: t.Record(t.String(), t.Any()),
    errorMessage: t.Nullable(t.String()),
  }),

  knowledgeCardsQuery: t.Object({
    limit: t.Optional(t.Number({ default: 50 })),
    dimension: t.Optional(t.Union([
      t.Literal('technical'),
      t.Literal('business'),
      t.Literal('personal'),
      t.Literal('project'),
      t.Literal('general'),
    ])),
    type: t.Optional(t.Union([
      t.Literal('fact'),
      t.Literal('insight'),
      t.Literal('decision'),
      t.Literal('task'),
      t.Literal('pattern'),
    ])),
    includeDeleted: t.Optional(t.Boolean({ default: false })),
  }),

  dreamStartBody: t.Object({
    runType: t.Optional(t.Union([
      t.Literal('archive'),
      t.Literal('merge'),
      t.Literal('prune'),
      t.Literal('restore'),
      t.Literal('dry-run'),
    ])),
    dryRun: t.Optional(t.Boolean()),
    limit: t.Optional(t.Number({ minimum: 2 })),
    similarityThreshold: t.Optional(t.Number({ minimum: 0.1, maximum: 1 })),
    applyMerge: t.Optional(t.Boolean()),
  }),

  activityPipelineTickResponse: t.Object({
    checked: t.Number(),
    triaged: t.Number(),
    summarized: t.Number(),
    crystallized: t.Number(),
    skipped: t.Number(),
    errors: t.Number(),
  }),

  activityPipelineAction: t.Object({
    segment: t.Object({
      id: t.String(),
      sessionId: t.String(),
      startedAt: t.String(),
      startedAtUnix: t.Number(),
      endedAt: t.String(),
      endedAtUnix: t.Number(),
      durationSeconds: t.Number(),
      segmentType: t.Union([
        t.Literal('work'),
        t.Literal('meeting'),
        t.Literal('browsing'),
        t.Literal('chat'),
        t.Literal('audio'),
        t.Literal('idle'),
        t.Literal('unknown'),
      ]),
      frontApp: t.Nullable(t.String()),
      title: t.Nullable(t.String()),
      summary: t.Nullable(t.String()),
      sourceCounts: t.Record(t.String(), t.Number()),
      sourceRefs: t.Record(t.String(), t.Array(t.String())),
      pipelineStatus: t.Union([
        t.Literal('collecting'),
        t.Literal('triaged'),
        t.Literal('summarized'),
        t.Literal('crystallized'),
        t.Literal('error'),
      ]),
      isCrystallized: t.Boolean(),
      metadata: t.Record(t.String(), t.Any()),
    }),
    run: t.Object({
      id: t.String(),
      sessionId: t.Nullable(t.String()),
      segmentId: t.Nullable(t.String()),
      trigger: t.Union([
        t.Literal('snapshot'),
        t.Literal('message'),
        t.Literal('audio-raw'),
        t.Literal('audio-transcript'),
        t.Literal('memory'),
        t.Literal('manual'),
        t.Literal('summarize'),
      ]),
      stage: t.Union([
        t.Literal('collection'),
        t.Literal('segmentation'),
        t.Literal('triage'),
        t.Literal('summarization'),
        t.Literal('crystallization'),
      ]),
      status: t.Union([
        t.Literal('queued'),
        t.Literal('running'),
        t.Literal('success'),
        t.Literal('error'),
        t.Literal('skipped'),
      ]),
      startedAt: t.String(),
      startedAtUnix: t.Number(),
      endedAt: t.Nullable(t.String()),
      endedAtUnix: t.Nullable(t.Number()),
      errorMessage: t.Nullable(t.String()),
      snapshotsCount: t.Number(),
      messagesCount: t.Number(),
      audioTranscriptsCount: t.Number(),
      audioRawSegmentsCount: t.Number(),
      memoriesCount: t.Number(),
      segmentsCount: t.Number(),
      segmentIds: t.Array(t.String()),
      metadata: t.Record(t.String(), t.Any()),
    }),
    memoryId: t.Nullable(t.String()),
    knowledgeCards: t.Optional(t.Array(t.Object({
      id: t.String(),
      title: t.String(),
      content: t.String(),
      cardType: t.Union([
        t.Literal('fact'),
        t.Literal('insight'),
        t.Literal('decision'),
        t.Literal('task'),
        t.Literal('pattern'),
      ]),
      dimension: t.Union([
        t.Literal('technical'),
        t.Literal('business'),
        t.Literal('personal'),
        t.Literal('project'),
        t.Literal('general'),
      ]),
      confidence: t.Number(),
      sourceMemoryIds: t.Array(t.String()),
      sourceSegmentIds: t.Array(t.String()),
      sourceChunkIds: t.Array(t.String()),
      tags: t.Array(t.String()),
      contentHash: t.String(),
      version: t.Number(),
      status: t.Union([
        t.Literal('active'),
        t.Literal('merged'),
        t.Literal('archived'),
        t.Literal('deleted'),
      ]),
      mergedIntoId: t.Nullable(t.String()),
      pinned: t.Boolean(),
      metadata: t.Record(t.String(), t.Any()),
      createdAt: t.String(),
      createdAtUnix: t.Number(),
      updatedAt: t.String(),
      updatedAtUnix: t.Number(),
    }))),
    status: t.Union([
      t.Literal('success'),
      t.Literal('error'),
      t.Literal('skipped'),
    ]),
    message: t.String(),
  }),

  audioRawSegmentReportBody: t.Object({
    sourceId: t.String({ minLength: 1 }),
    recordedAt: t.String({ minLength: 1 }),
    source: t.Optional(t.Union([t.Literal('microphone'), t.Literal('system'), t.Literal('mixed')])),
    status: t.Optional(t.Union([
      t.Literal('captured'),
      t.Literal('queued'),
      t.Literal('processed'),
      t.Literal('ignored'),
      t.Literal('error'),
    ])),
    audioPath: t.String({ minLength: 1 }),
    metadataPath: t.String({ minLength: 1 }),
    sampleRate: t.Number({ minimum: 1 }),
    channels: t.Number({ minimum: 1 }),
    sampleCount: t.Number({ minimum: 0 }),
    droppedSamples: t.Optional(t.Number({ minimum: 0 })),
    durationMs: t.Optional(t.Number({ minimum: 0 })),
    rms: t.Number({ minimum: 0, maximum: 1 }),
    peak: t.Number({ minimum: 0, maximum: 1 }),
    active: t.Boolean(),
    vadImplemented: t.Optional(t.Boolean()),
    asrImplemented: t.Optional(t.Boolean()),
    speakerLabelingImplemented: t.Optional(t.Boolean()),
    metadata: t.Optional(t.Record(t.String(), t.Any())),
  }),

  accessibilitySnapshot: t.Object({
    id: t.String(),
    sourceId: t.String(),
    snapshotId: t.Nullable(t.String()),
    capturedAt: t.String(),
    capturedAtUnix: t.Number(),
    status: t.Union([
      t.Literal('ready'),
      t.Literal('permission-denied'),
      t.Literal('unavailable'),
      t.Literal('error'),
    ]),
    provider: t.String(),
    appBundleId: t.Nullable(t.String()),
    windowTitle: t.Nullable(t.String()),
    elementCount: t.Number(),
    text: t.Nullable(t.String()),
    tree: t.Array(t.Any()),
    metadata: t.Record(t.String(), t.Any()),
  }),

  accessibilitySnapshotReportBody: t.Object({
    sourceId: t.String({ minLength: 1 }),
    status: t.Optional(t.Union([
      t.Literal('ready'),
      t.Literal('permission-denied'),
      t.Literal('unavailable'),
      t.Literal('error'),
    ])),
    provider: t.Optional(t.String()),
    accessibilityPath: t.Optional(t.Nullable(t.String())),
    text: t.Optional(t.Nullable(t.String())),
    elementCount: t.Optional(t.Number({ minimum: 0 })),
    appBundleId: t.Optional(t.Nullable(t.String())),
    windowTitle: t.Optional(t.Nullable(t.String())),
    tree: t.Optional(t.Array(t.Any())),
    metadata: t.Optional(t.Record(t.String(), t.Any())),
  }),

  slackSyncResponse: t.Object({
    sourceId: t.String(),
    status: t.Union([t.Literal('success'), t.Literal('error')]),
    ingested: t.Number(),
    message: t.String(),
  }),

  slackEventsResponse: t.Object({
    sourceId: t.String(),
    status: t.Union([t.Literal('ok'), t.Literal('ignored')]),
    ingested: t.Number(),
    message: t.String(),
    challenge: t.Optional(t.String()),
  }),

  summarizeBody: t.Object({
    prompt: t.String({ minLength: 1 }),
    windowType: t.Union([t.Literal('10min'), t.Literal('6h')]),
    sourceSnapshotIds: t.Optional(t.Array(t.String())),
    sourceArtifactPaths: t.Optional(t.Array(t.String())),
  }),

  summarizeResponse: t.Object({
    summary: t.String(),
    memoryId: t.Nullable(t.String()),
    status: t.Union([t.Literal('success'), t.Literal('error')]),
  }),

  snapshotReportBody: t.Object({
    sourceId: t.String({ minLength: 1 }),
    displayId: t.Number(),
    frameIndex: t.Optional(t.Number()),
    capturedAt: t.String({ minLength: 1 }),
    segmentDir: t.String(),
    framePath: t.String(),
    capturePath: t.Optional(t.String()),
    ocrPath: t.Optional(t.String()),
    snapshotPath: t.Optional(t.String()),
    ocrText: t.Optional(t.String()),
    appBundleId: t.Optional(t.String()),
    windowTitle: t.Optional(t.String()),
    accessibility: t.Optional(t.Object({
      sourceId: t.String({ minLength: 1 }),
      status: t.Optional(t.Union([
        t.Literal('ready'),
        t.Literal('permission-denied'),
        t.Literal('unavailable'),
        t.Literal('error'),
      ])),
      provider: t.Optional(t.String()),
      accessibilityPath: t.Optional(t.Nullable(t.String())),
      text: t.Optional(t.Nullable(t.String())),
      elementCount: t.Optional(t.Number({ minimum: 0 })),
      appBundleId: t.Optional(t.Nullable(t.String())),
      windowTitle: t.Optional(t.Nullable(t.String())),
      tree: t.Optional(t.Array(t.Any())),
      metadata: t.Optional(t.Record(t.String(), t.Any())),
    })),
    metadata: t.Optional(t.Record(t.String(), t.Any())),
  }),

  memoryReportBody: t.Object({
    sourceId: t.String({ minLength: 1 }),
    windowType: t.Union([t.Literal('10min'), t.Literal('6h')]),
    createdAt: t.String({ minLength: 1 }),
    memoryPath: t.Optional(t.String()),
    content: t.String(),
    summaryKind: t.Union([t.Literal('llm'), t.Literal('local'), t.Literal('imported')]),
    sourceSnapshotPaths: t.Optional(t.Array(t.String())),
    sourceFramePaths: t.Optional(t.Array(t.String())),
    metadata: t.Optional(t.Record(t.String(), t.Any())),
  }),

  status: t.Object({
    available: t.Boolean(),
    running: t.Boolean(),
    pid: t.Nullable(t.Number()),
    lastCaptureAt: t.Nullable(t.Number()),
    lastSummaryAt: t.Nullable(t.Number()),
    lastErrorAt: t.Nullable(t.Number()),
    lastError: t.Nullable(t.String()),
    lastExitCode: t.Nullable(t.Number()),
    lastExitAt: t.Nullable(t.Number()),
    totalSnapshots: t.Number(),
    totalSummaries: t.Number(),
    totalMessages: t.Number(),
    lastMessageAt: t.Nullable(t.Number()),
    totalAccessibilitySnapshots: t.Number(),
    lastAccessibilitySnapshotAt: t.Nullable(t.Number()),
    totalAudioTranscripts: t.Number(),
    lastAudioTranscriptAt: t.Nullable(t.Number()),
    totalAudioRawSegments: t.Number(),
    lastAudioRawSegmentAt: t.Nullable(t.Number()),
    totalActivitySegments: t.Number(),
    lastActivitySegmentAt: t.Nullable(t.Number()),
    totalPipelineRuns: t.Number(),
    lastPipelineRunAt: t.Nullable(t.Number()),
    totalKnowledgeCards: t.Number(),
    lastKnowledgeCardAt: t.Nullable(t.Number()),
    totalDreamRuns: t.Number(),
    lastDreamRunAt: t.Nullable(t.Number()),
    activityPipelineEnabled: t.Boolean(),
    activityPipelineRunning: t.Boolean(),
    activityPipelineIntervalMs: t.Number(),
    activityPipelineBatchSize: t.Number(),
    audioCaptureEnabled: t.Boolean(),
    audioRuntimeStatus: t.Union([
      t.Literal('disabled'),
      t.Literal('armed'),
      t.Literal('unavailable'),
    ]),
    configuredModel: t.Nullable(t.String()),
  }),
}
