import { t } from 'elysia'

export const ObservabilityModel = {
  createEventBody: t.Object({
    source: t.String(),
    code: t.String(),
    severity: t.String(),
    category: t.String(),
    message: t.String(),
    attrs: t.Optional(t.Record(t.String(), t.Unknown())),
    chatSessionId: t.Optional(t.String()),
    runId: t.Optional(t.String()),
    messageId: t.Optional(t.String()),
    traceId: t.Optional(t.String()),
    dedupeKey: t.Optional(t.String()),
    parentEventId: t.Optional(t.String()),
    occurredAt: t.Optional(t.Number()),
    recordedAt: t.Optional(t.Number()),
  }),

  createEventResponse: t.Object({
    ok: t.Literal(true),
  }),

  event: t.Object({
    id: t.String(),
    schemaVersion: t.Number(),
    source: t.String(),
    code: t.String(),
    severity: t.String(),
    category: t.String(),
    message: t.String(),
    attrs: t.Optional(t.Record(t.String(), t.Unknown())),
    chatSessionId: t.Optional(t.String()),
    runId: t.Optional(t.String()),
    messageId: t.Optional(t.String()),
    traceId: t.Optional(t.String()),
    dedupeKey: t.Optional(t.String()),
    parentEventId: t.Optional(t.String()),
    occurredAt: t.Number(),
    recordedAt: t.Number(),
  }),

  incident: t.Object({
    id: t.String(),
    dedupeKey: t.String(),
    code: t.String(),
    severity: t.String(),
    status: t.Union([t.Literal('open'), t.Literal('resolved')]),
    source: t.String(),
    message: t.String(),
    chatSessionId: t.Optional(t.String()),
    runId: t.Optional(t.String()),
    messageId: t.Optional(t.String()),
    firstOccurredAt: t.Number(),
    lastOccurredAt: t.Number(),
    lastRecordedAt: t.Number(),
    count: t.Number(),
    lastEventId: t.Optional(t.String()),
    attrs: t.Optional(t.Record(t.String(), t.Unknown())),
  }),

  bundle: t.Object({
    schema: t.String(),
    exportedAt: t.Number(),
    metadata: t.Record(t.String(), t.Unknown()),
    redaction: t.Record(t.String(), t.Unknown()),
    events: t.Array(t.Object({
      id: t.String(),
      schemaVersion: t.Number(),
      source: t.String(),
      code: t.String(),
      severity: t.String(),
      category: t.String(),
      message: t.String(),
      attrs: t.Optional(t.Record(t.String(), t.Unknown())),
      chatSessionId: t.Optional(t.String()),
      runId: t.Optional(t.String()),
      messageId: t.Optional(t.String()),
      traceId: t.Optional(t.String()),
      dedupeKey: t.Optional(t.String()),
      parentEventId: t.Optional(t.String()),
      occurredAt: t.Number(),
      recordedAt: t.Number(),
    })),
    incidents: t.Array(t.Object({
      id: t.String(),
      dedupeKey: t.String(),
      code: t.String(),
      severity: t.String(),
      status: t.Union([t.Literal('open'), t.Literal('resolved')]),
      source: t.String(),
      message: t.String(),
      chatSessionId: t.Optional(t.String()),
      runId: t.Optional(t.String()),
      messageId: t.Optional(t.String()),
      firstOccurredAt: t.Number(),
      lastOccurredAt: t.Number(),
      lastRecordedAt: t.Number(),
      count: t.Number(),
      lastEventId: t.Optional(t.String()),
      attrs: t.Optional(t.Record(t.String(), t.Unknown())),
    })),
    timeline: t.Array(t.Record(t.String(), t.Unknown())),
    logs: t.Record(t.String(), t.Unknown()),
  }),

  eventsQuery: t.Object({
    chatSessionId: t.Optional(t.String()),
    runId: t.Optional(t.String()),
    code: t.Optional(t.String()),
    severity: t.Optional(t.String()),
    since: t.Optional(t.String()),
    until: t.Optional(t.String()),
    limit: t.Optional(t.String()),
  }),

  incidentsQuery: t.Object({
    dedupeKey: t.Optional(t.String()),
    chatSessionId: t.Optional(t.String()),
    runId: t.Optional(t.String()),
    code: t.Optional(t.String()),
    status: t.Optional(t.Union([t.Literal('open'), t.Literal('resolved')])),
    limit: t.Optional(t.String()),
  }),

  exportQuery: t.Object({
    chatSessionId: t.Optional(t.String()),
    runId: t.Optional(t.String()),
    sinceUnix: t.Optional(t.String()),
  }),

  flushResponse: t.Object({
    ok: t.Literal(true),
  }),
}
